-- 实时文档相关表
CREATE TABLE `t_realtime_doc` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `doc_id` bigint NOT NULL COMMENT '文档ID',
    `session_id` varchar(255) NOT NULL COMMENT '会话SessionID',
    `cos_url_id` bigint NOT NULL COMMENT 'cos文件地址ID',
    `robot_id` bigint NOT NULL COMMENT '企业ID',
    `corp_id` bigint NOT NULL COMMENT '企业ID',
    `staff_id` bigint NOT NULL DEFAULT '0' COMMENT '员工ID',
    `file_name` varchar(255) NOT NULL COMMENT '文件名',
    `file_type` varchar(32) NOT NULL COMMENT '文档类型',
    `file_size` bigint NOT NULL DEFAULT '0' COMMENT '文件大小(字节)',
    `bucket` varchar(255) NOT NULL COMMENT 'cos bucket',
    `cos_url` varchar(1024) NOT NULL COMMENT 'cos文件地址',
    `cos_hash` varchar(255) NOT NULL COMMENT 'x-cos-hash-crc64ecma 头部中的 CRC64编码进行校验上传到云端的文件和本地文件的一致性',
    `char_size` bigint NOT NULL DEFAULT '0' COMMENT '文档字符数',
    `file_full_text` longtext COMMENT '文档全文（不为空表示满足条件可以直接使用，为空不能直接使用）',
    `message` varchar(1024) NOT NULL DEFAULT '' COMMENT '失败原因',
    `status` varchar(32) NOT NULL DEFAULT 'INIT' COMMENT '状态(INIT: 初始化；PARSING:解析中；LEARNING:学习中；SUCCESS:成功；FAILED:失败；CANCEL:取消)',
    `request_id` varchar(255) NOT NULL DEFAULT '' COMMENT '文档解析任务请求唯一id',
    `task_id` varchar(255) NOT NULL DEFAULT '' COMMENT '文档解析任务TaskID',
    `op_type` int NOT NULL DEFAULT '0' COMMENT '文档解析任务类型（0:未知；1:文档解析；2:取消解析）',
    `result` text COMMENT '文档解析任务结果',
    `task_status` int NOT NULL DEFAULT '-1' COMMENT '状态(-1:未知；0:成功；1：失败)',
    `progress` int NOT NULL DEFAULT '0' COMMENT ' 进度（0~100）',
    `progress_message` varchar(1024) NOT NULL DEFAULT '' COMMENT 'cos文件地址',
    `is_deleted` int NOT NULL DEFAULT '0' COMMENT '是否删除(0未删除 1已删除）',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`, `create_time`),
    UNIQUE KEY `uni_doc_id` (`doc_id`),
    UNIQUE KEY `uni_session_id_cos_url_id` (`session_id`, `cos_url_id`),
    KEY `uni_corp_cos_hash` (`corp_id`, `cos_hash`),
    KEY `idx_corp_robot` (`corp_id`, `robot_id`)
) ENGINE = InnoDB AUTO_INCREMENT = 0 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '实时文档表';

CREATE TABLE `t_realtime_doc_segment` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `segment_id` bigint NOT NULL COMMENT '切片ID',
    `session_id` varchar(255) NOT NULL COMMENT '会话SessionID',
    `doc_id` bigint NOT NULL COMMENT '文档ID',
    `robot_id` bigint NOT NULL COMMENT '机器人ID',
    `corp_id` bigint NOT NULL COMMENT '企业ID',
    `staff_id` bigint NOT NULL COMMENT '员工ID',
    `file_type` varchar(255) NOT NULL COMMENT '文件类型',
    `segment_type` varchar(64)  NOT NULL DEFAULT '' COMMENT '文档切片类型 segment-文档切片 table-表格',
    `title` varchar(1024) NOT NULL DEFAULT '' COMMENT '章节标题',
    `page_content` longtext NOT NULL COMMENT '段落内容',
    `org_data` longtext NOT NULL COMMENT '原始内容',
    `split_model` varchar(50) NOT NULL COMMENT '分割模式line:按行 window:按窗口',
    `is_sync_knowledge` int NOT NULL DEFAULT '0' COMMENT '是否同步知识(0未同步 1已同步）',
    `is_deleted` int NOT NULL DEFAULT '0' COMMENT '1未删除 2已删除',
    `rich_text_index` int NOT NULL DEFAULT '0' COMMENT 'rich text index',
    `start_index` int NOT NULL DEFAULT '0' COMMENT '分片起始索引',
    `end_index` int NOT NULL DEFAULT '0' COMMENT '分片结束索引',
    `linker_keep` tinyint NOT NULL DEFAULT '0' COMMENT '连续文档合并时是否保持不做合并',
    `big_data_id` varchar(64)  NOT NULL DEFAULT '' COMMENT 'big_data标识id',
    `big_start_index` int NOT NULL DEFAULT '0' COMMENT 'big_data起始偏移位置',
    `big_end_index` int NOT NULL DEFAULT '0' COMMENT 'big_data结束偏移位置',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '响应时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uni_segment_id` (`segment_id`),
    KEY `idx_corp_robot` (`corp_id`, `robot_id`),
    KEY `idx_doc_id` (`doc_id`)
) ENGINE = InnoDB AUTO_INCREMENT = 0 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '实时文档分片';


CREATE TABLE `t_msg_record_like_count_hour` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键自增ID',
    `bot_biz_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT '机器人ID',
    `total_count` int(11) NOT NULL DEFAULT 0 COMMENT '消息总数',
    `like_count` int(11) NOT NULL DEFAULT 0 COMMENT '点赞总数',
    `dislike_count` int(11) NOT NULL DEFAULT 0 COMMENT '点踩总数',
    `type` tinyint NOT NULL COMMENT '消息类型',
    `day` date NOT NULL COMMENT '统计日期天',
    `hour` int NOT NULL COMMENT '统计日期小时',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_bot_biz_id_from_type_date` (`bot_biz_id`,`type`, `day`, `hour`),
    KEY `idx_bot_biz_id` (`bot_biz_id`),
    KEY `idx_type` (`type`),
    KEY `idx_date` (`day`,`hour`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '点赞点踩小时统计表'

CREATE TABLE `t_msg_record_reply_count_hour` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键自增ID',
    `bot_biz_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT '机器人ID',
    `total_count` int(11) NOT NULL DEFAULT 0 COMMENT '消息总数',
    `model_reply_count` int(11) NOT NULL DEFAULT 0 COMMENT '大模型直接回复总数',
    `knowledge_count` int(11) NOT NULL DEFAULT 0 COMMENT '知识型回复总数',
    `task_flow_count` int(11) NOT NULL DEFAULT 0 COMMENT '任务流回复总数',
    `search_engine_count` int(11) NOT NULL DEFAULT 0 COMMENT '搜索引擎回复总数',
    `image_understanding_count` int(11) NOT NULL DEFAULT 0 COMMENT '图片理解回复总数',
    `reject_count` int(11) NOT NULL DEFAULT 0 COMMENT '拒答回复总数',
    `sensitive_count` int(11) NOT NULL DEFAULT 0 COMMENT '敏感回复总数',
    `concurrent_limit_count` int(11) NOT NULL DEFAULT 0 COMMENT '并发超限回复总数',
    `unknown_issues_count` int(11) NOT NULL DEFAULT 0 COMMENT '未知问题回复总数',
    `type` tinyint NOT NULL COMMENT '消息类型',
    `to_type` tinyint NOT NULL COMMENT '消息类型',
    `day` date NOT NULL COMMENT '统计日期天',
    `hour` int NOT NULL COMMENT '统计日期小时',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_bot_biz_id_type_date` (`bot_biz_id`,`type`,`to_type`, `day`, `hour`),
    KEY `idx_bot_biz_id` (`bot_biz_id`),
    KEY `idx_type` (`type`,`to_type`),
    KEY `idx_date` (`day`,`hour`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '回答类型小时统计表'