-- 数据库表更记录：
-- 1. 增加了release_status  next_action 字段
-- 2. biz ID 修改为unique key了
-- 3. db_table 相关的三张表，新增 is_index  字段，表示该表是否参与检索
-- 4. db_table 相关的三张表，新增 alive 字段，表示外部数据库是否将表删除
CREATE TABLE `t_db_source` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `corp_biz_id` bigint NOT NULL COMMENT '企业业务ID',
    `app_biz_id` bigint NOT NULL COMMENT '应用业务ID',
    `db_source_biz_id` bigint NOT NULL COMMENT '新产生的ID，雪花算法 id ',
    `db_name` varchar(100) NOT NULL COMMENT '原始的数据库名称',
    `alias_name` varchar(100) NOT NULL COMMENT '自定义数据库名称',
    `description` text COMMENT '数据库描述',
    `db_type` varchar(32) NOT NULL COMMENT '数据库类型: mysql, sqlserver',
    `host` varchar(100) NOT NULL COMMENT '地址',
    `port` int NOT NULL COMMENT '端口号',
    `username` varchar(100) NOT NULL COMMENT '用户名',
    `password` varchar(255) NOT NULL COMMENT '加密存储的密码',
    `alive` tinyint(1) NOT NULL DEFAULT 1 COMMENT '连接是否正常',
    `last_sync_time` datetime DEFAULT NULL COMMENT '上次同步时间',
    `release_status` tinyint NOT NULL DEFAULT 0 COMMENT '发布状态(1 待发布 2 发布中 3 已发布 4 发布失败)',
    `next_action` tinyint NOT NULL DEFAULT 0 COMMENT '最后操作：1新增 2修改 3删除 4发布',
    `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0:未删除,1:已删除',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`, `app_biz_id`),
    UNIQUE KEY `idx_biz_id` (`corp_biz_id`, `app_biz_id`, `db_source_biz_id`),
    KEY `idx_app_id_release` (`app_biz_id`, `release_status`),
    KEY `idx_db_biz_id` (`db_source_biz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据库连接信息表' shardkey=app_biz_id;

CREATE TABLE `t_release_db_source` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `corp_biz_id` bigint NOT NULL COMMENT '企业业务ID',
    `app_biz_id` bigint NOT NULL COMMENT '应用业务ID',
    `db_source_biz_id` bigint NOT NULL COMMENT '新产生的ID，雪花算法 id ',
    `db_name` varchar(100) NOT NULL COMMENT '原始的数据库名称',
    `alias_name` varchar(100) NOT NULL COMMENT '自定义数据库名称',
    `description` text COMMENT '数据库描述',
    `db_type` varchar(32) NOT NULL COMMENT '数据库类型: mysql, sqlserver',
    `host` varchar(100) NOT NULL COMMENT '地址',
    `port` int NOT NULL COMMENT '端口号',
    `username` varchar(100) NOT NULL COMMENT '用户名',
    `password` varchar(255) NOT NULL COMMENT '加密存储的密码',
    `alive` tinyint(1) NOT NULL DEFAULT 1 COMMENT '连接是否正常',
    `last_sync_time` datetime DEFAULT NULL COMMENT '上次同步时间',
    `release_status` tinyint NOT NULL DEFAULT 0 COMMENT '发布状态(1 待发布 2 发布中 3 已发布 4 发布失败)',
    `release_biz_id` bigint NOT NULL DEFAULT '0' COMMENT '版本ID',
    `action` tinyint NOT NULL DEFAULT 0 COMMENT '操作行为：1新增 2修改 3删除 4发布',
    `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0:未删除,1:已删除',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`, `app_biz_id`),
    UNIQUE KEY `idx_biz_id` (`corp_biz_id`, `app_biz_id`, `db_source_biz_id`, `release_biz_id`),
    KEY `idx_app_id_release` (`app_biz_id`, `release_biz_id`),
    KEY `idx_db_biz_id` (`db_source_biz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据库连接信息发布表' shardkey=app_biz_id;

CREATE TABLE `t_db_source_prod` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `corp_biz_id` bigint NOT NULL COMMENT '企业业务ID',
    `app_biz_id` bigint NOT NULL COMMENT '应用业务ID',
    `db_source_biz_id` bigint NOT NULL COMMENT '新产生的ID，雪花算法 id ',
    `db_name` varchar(100) NOT NULL COMMENT '原始的数据库名称',
    `alias_name` varchar(100) NOT NULL COMMENT '自定义数据库名称',
    `description` text COMMENT '数据库描述',
    `db_type` varchar(32) NOT NULL COMMENT '数据库类型: mysql, sqlserver',
    `host` varchar(100) NOT NULL COMMENT '地址',
    `port` int NOT NULL COMMENT '端口号',
    `username` varchar(100) NOT NULL COMMENT '用户名',
    `password` varchar(255) NOT NULL COMMENT '加密存储的密码',
    `alive` tinyint(1) NOT NULL DEFAULT 1 COMMENT '连接是否正常',
    `last_sync_time` datetime DEFAULT NULL COMMENT '上次同步时间',
    `release_status` tinyint NOT NULL DEFAULT 0 COMMENT '发布状态(1 待发布 2 发布中 3 已发布 4 发布失败)',
    `next_action` tinyint NOT NULL DEFAULT 0 COMMENT '最后操作：1新增 2修改 3删除 4发布',
    `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0:未删除,1:已删除',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`, `app_biz_id`),
    UNIQUE KEY `idx_biz_id` (`corp_biz_id`, `app_biz_id`, `db_source_biz_id`),
    KEY `idx_db_biz_id` (`db_source_biz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据库连接信息正式环境表' shardkey=app_biz_id;

--------------

CREATE TABLE `t_db_table` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `corp_biz_id` bigint NOT NULL COMMENT '企业业务ID',
    `app_biz_id` bigint NOT NULL COMMENT '应用业务ID',
    `db_source_biz_id` bigint NOT NULL COMMENT '数据源ID',
    `db_table_biz_id` bigint NOT NULL COMMENT '雪花算法 id',
    `source` tinyint NOT NULL DEFAULT 0 COMMENT '来源(0 外部数据库 1 文档text2sql)',
    `table_name` varchar(100) NOT NULL COMMENT '表名',
    `table_schema` varchar(100) NOT NULL COMMENT '库名',
    `table_comment` varchar(1500) DEFAULT '' COMMENT '列注释',
    `alias_name` varchar(100) DEFAULT '' COMMENT '表中文名',
    `description` varchar(500) DEFAULT '' COMMENT '表描述',
    `row_count` bigint DEFAULT 0 COMMENT '行数',
    `column_count` int DEFAULT 0 COMMENT '列数',
    `table_added_time` datetime DEFAULT NULL COMMENT '表被选择加入知识库的时间',
    `table_modified_time` datetime DEFAULT NULL COMMENT '表，或者列更新的时间',
    `last_sync_time` datetime DEFAULT NULL COMMENT '上次同步时间',
    `release_status` tinyint NOT NULL DEFAULT 0 COMMENT '发布状态(1 待发布 2 发布中 3 已发布 4 发布失败)',
    `next_action` tinyint NOT NULL  DEFAULT 0 COMMENT '最后操作：1新增 2修改 3删除 4发布',
    `alive` tinyint(1) DEFAULT 1 COMMENT '外部数据表是否存活',
    `is_indexed` tinyint(1) DEFAULT 1 COMMENT '是否参与索引',
    `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '软删除标记',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`, `app_biz_id`),
    UNIQUE KEY `idx_table_id` (`corp_biz_id`, `app_biz_id`, `db_table_biz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='表数据' shardkey=app_biz_id;

CREATE TABLE `t_release_db_table` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `corp_biz_id` bigint NOT NULL COMMENT '企业业务ID',
    `app_biz_id` bigint NOT NULL COMMENT '应用业务ID',
    `db_source_biz_id` bigint NOT NULL COMMENT '数据源ID',
    `db_table_biz_id` bigint NOT NULL COMMENT '雪花算法 id',
    `source` tinyint NOT NULL DEFAULT 0 COMMENT '来源(0 外部数据库 1 文档text2sql)',
    `table_name` varchar(100) NOT NULL COMMENT '表名',
    `table_schema` varchar(100) NOT NULL COMMENT '库名',
    `table_comment` varchar(1500) DEFAULT '' COMMENT '列注释',
    `alias_name` varchar(100) DEFAULT '' COMMENT '表中文名',
    `description` varchar(500) DEFAULT '' COMMENT '表描述',
    `row_count` bigint DEFAULT 0 COMMENT '行数',
    `column_count` int DEFAULT 0 COMMENT '列数',
    `table_added_time` datetime DEFAULT NULL COMMENT '表被选择加入知识库的时间',
    `table_modified_time` datetime DEFAULT NULL COMMENT '表，或者列更新的时间',
    `last_sync_time` datetime DEFAULT NULL COMMENT '上次同步时间',
    `release_status` tinyint NOT NULL DEFAULT 0 COMMENT '发布状态(1 待发布 2 发布中 3 已发布 4 发布失败)',
    `release_biz_id` bigint NOT NULL DEFAULT '0' COMMENT '版本ID',
    `action` tinyint NOT NULL DEFAULT 0 COMMENT '操作行为：1新增2修改3删除 4发布',
    `alive` tinyint(1) DEFAULT 1 COMMENT '外部数据表是否存活',
    `is_indexed` tinyint(1) DEFAULT 1 COMMENT '是否参与索引',
    `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '软删除标记',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`, `app_biz_id`),
    UNIQUE KEY `idx_table_id` (`corp_biz_id`, `app_biz_id`, `db_table_biz_id`, `release_biz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='表数据发布表' shardkey=app_biz_id;

CREATE TABLE `t_db_table_prod` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `corp_biz_id` bigint NOT NULL COMMENT '企业业务ID',
    `app_biz_id` bigint NOT NULL COMMENT '应用业务ID',
    `db_source_biz_id` bigint NOT NULL COMMENT '数据源ID',
    `db_table_biz_id` bigint NOT NULL COMMENT '雪花算法 id',
    `source` tinyint NOT NULL DEFAULT 0 COMMENT '来源(0 外部数据库 1 文档text2sql)',
    `table_name` varchar(100) NOT NULL COMMENT '表名',
    `table_schema` varchar(100) NOT NULL COMMENT '库名',
    `table_comment` varchar(1500) DEFAULT '' COMMENT '列注释',
    `alias_name` varchar(100) DEFAULT '' COMMENT '表中文名',
    `description` varchar(500) DEFAULT '' COMMENT '表描述',
    `row_count` bigint DEFAULT 0 COMMENT '行数',
    `column_count` int DEFAULT 0 COMMENT '列数',
    `table_added_time` datetime DEFAULT NULL COMMENT '表被选择加入知识库的时间',
    `table_modified_time` datetime DEFAULT NULL COMMENT '表，或者列更新的时间',
    `last_sync_time` datetime DEFAULT NULL COMMENT '上次同步时间',
    `release_status` tinyint NOT NULL DEFAULT 0 COMMENT '发布状态(1 待发布 2 发布中 3 已发布 4 发布失败)',
    `next_action` tinyint NOT NULL  DEFAULT 0 COMMENT '最后操作：1新增 2修改 3删除 4发布',
    `alive` tinyint(1) DEFAULT 1 COMMENT '外部数据表是否存活',
    `is_indexed` tinyint(1) DEFAULT 1 COMMENT '是否参与索引',
    `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '软删除标记',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`, `app_biz_id`),
    UNIQUE KEY `idx_table_id` (`corp_biz_id`, `app_biz_id`, `db_table_biz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='正式环境表数据' shardkey=app_biz_id;
------

CREATE TABLE `t_db_table_column` (
     `id` bigint NOT NULL AUTO_INCREMENT,
     `corp_biz_id` bigint NOT NULL COMMENT '企业业务ID',
     `app_biz_id` bigint NOT NULL COMMENT '应用业务ID',
     `db_table_biz_id` bigint NOT NULL COMMENT '表元数据ID',
     `db_table_column_biz_id` bigint NOT NULL COMMENT '列数据ID',
     `column_name` varchar(100) NOT NULL COMMENT '列名',
     `data_type` varchar(32) NOT NULL COMMENT '数据类型, ',
     `column_comment` varchar(1500) DEFAULT '' COMMENT '列注释',
     `alias_name` varchar(100) DEFAULT '' COMMENT '别名',
     `description` varchar(500) DEFAULT '' COMMENT '列描述',
     `unit` varchar(50) DEFAULT '' COMMENT '单位',
     `is_indexed` tinyint(1) DEFAULT 0 COMMENT '是否参与索引',
     `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '软删除标记',
     `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
     `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
     PRIMARY KEY (`id`, `app_biz_id`),
     UNIQUE KEY `idx_column_id` (`corp_biz_id`, `app_biz_id`, `db_table_column_biz_id`),
     KEY `idx_table_column_id` (`corp_biz_id`, `app_biz_id`,`db_table_biz_id`, `db_table_column_biz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='列数据' shardkey=app_biz_id;
