// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"git.code.oa.com/trpc-go/trpc-go/http"
	"git.woa.com/adp/common/x/clientx/s3x"
	"git.woa.com/adp/kb/kb-config/internal/dao"
	"git.woa.com/adp/kb/kb-config/internal/dao/category"
	"git.woa.com/adp/kb/kb-config/internal/dao/database"
	"git.woa.com/adp/kb/kb-config/internal/dao/document"
	"git.woa.com/adp/kb/kb-config/internal/dao/export"
	"git.woa.com/adp/kb/kb-config/internal/dao/kb"
	"git.woa.com/adp/kb/kb-config/internal/dao/label"
	"git.woa.com/adp/kb/kb-config/internal/dao/llm"
	"git.woa.com/adp/kb/kb-config/internal/dao/qa"
	"git.woa.com/adp/kb/kb-config/internal/dao/release"
	"git.woa.com/adp/kb/kb-config/internal/dao/segment"
	"git.woa.com/adp/kb/kb-config/internal/dao/third_document"
	"git.woa.com/adp/kb/kb-config/internal/dao/user"
	"git.woa.com/adp/kb/kb-config/internal/dao/vector"
	"git.woa.com/adp/kb/kb-config/internal/logic"
	"git.woa.com/adp/kb/kb-config/internal/logic/app"
	"git.woa.com/adp/kb/kb-config/internal/logic/audit"
	category2 "git.woa.com/adp/kb/kb-config/internal/logic/category"
	database2 "git.woa.com/adp/kb/kb-config/internal/logic/database"
	document2 "git.woa.com/adp/kb/kb-config/internal/logic/document"
	export2 "git.woa.com/adp/kb/kb-config/internal/logic/export"
	"git.woa.com/adp/kb/kb-config/internal/logic/finance"
	kb2 "git.woa.com/adp/kb/kb-config/internal/logic/kb"
	label2 "git.woa.com/adp/kb/kb-config/internal/logic/label"
	llm2 "git.woa.com/adp/kb/kb-config/internal/logic/llm"
	"git.woa.com/adp/kb/kb-config/internal/logic/localcache"
	qa2 "git.woa.com/adp/kb/kb-config/internal/logic/qa"
	release2 "git.woa.com/adp/kb/kb-config/internal/logic/release"
	segment2 "git.woa.com/adp/kb/kb-config/internal/logic/segment"
	"git.woa.com/adp/kb/kb-config/internal/logic/task"
	"git.woa.com/adp/kb/kb-config/internal/logic/third_document"
	user2 "git.woa.com/adp/kb/kb-config/internal/logic/user"
	vector2 "git.woa.com/adp/kb/kb-config/internal/logic/vector"
	"git.woa.com/adp/kb/kb-config/internal/rpc"
	"git.woa.com/adp/pb-go/app/app_config"
	"git.woa.com/adp/pb-go/kb/kb_retrieval"
	"git.woa.com/adp/pb-go/platform/platform_manager"
	"git.woa.com/adp/pb-go/resource_gallery/resource_gallery"
	"git.woa.com/dialogue-platform/lke_proto/pb-protocol/KEP"
	"git.woa.com/dialogue-platform/lke_proto/pb-protocol/bot_data_statistics_server"
	"git.woa.com/dialogue-platform/proto/pb-stub/access-manager-server"
	"git.woa.com/dialogue-platform/proto/pb-stub/embedding_server"
	"git.woa.com/dialogue-platform/proto/pb-stub/file_manager_server"
	"git.woa.com/dialogue-platform/proto/pb-stub/nrt_file_manager_server"
	"git.woa.com/dialogue-platform/proto/pb-stub/vector_db_manager"
	"git.woa.com/dialogue-platform/proto/pb-stub/web-parser-server"
	finance2 "git.woa.com/ivy/protobuf/trpc-go/qbot/finance/finance"
	"git.woa.com/ivy/protobuf/trpc-go/qbot/qbot/infosec"
	"git.woa.com/ivy/protobuf/trpc-go/qbot/qbot/short_url"
	"github.com/google/wire"
)

import (
	_ "git.code.oa.com/trpc-go/trpc-config-rainbow"
)

// Injectors from wire.go:

func newCmdService() *CmdService {
	adminClientProxy := _wireAdminClientProxyValue
	platform_managerAdminClientProxy := _wirePlatform_managerAdminClientProxyValue
	loginClientProxy := _wireLoginClientProxyValue
	directIndexClientProxy := _wireDirectIndexClientProxyValue
	retrievalClientProxy := _wireRetrievalClientProxyValue
	taskConfigClientProxy := _wireTaskConfigClientProxyValue
	tDocLinkerHTTP := _wireClientValue
	managerObjClientProxy := _wireManagerObjClientProxyValue
	embeddingObjClientProxy := _wireEmbeddingObjClientProxyValue
	financeClientProxy := _wireFinanceClientProxyValue
	infosecClientProxy := _wireInfosecClientProxyValue
	short_urlAdminClientProxy := _wireShort_urlAdminClientProxyValue
	parserObjClientProxy := _wireParserObjClientProxyValue
	nrt_file_manager_serverManagerObjClientProxy := _wireNrt_file_manager_serverManagerObjClientProxyValue
	accessManagerClientProxy := _wireAccessManagerClientProxyValue
	resource_galleryAdminClientProxy := _wireResource_galleryAdminClientProxyValue
	client := rpc.NewOpenAiClient()
	vectorObjClientProxy := _wireVectorObjClientProxyValue
	apiClientProxy := _wireApiClientProxyValue
	rpcRPC := rpc.New(adminClientProxy, platform_managerAdminClientProxy, loginClientProxy, directIndexClientProxy, retrievalClientProxy, taskConfigClientProxy, tDocLinkerHTTP, managerObjClientProxy, embeddingObjClientProxy, financeClientProxy, infosecClientProxy, short_urlAdminClientProxy, parserObjClientProxy, nrt_file_manager_serverManagerObjClientProxy, accessManagerClientProxy, resource_galleryAdminClientProxy, client, vectorObjClientProxy, apiClientProxy)
	config := dao.NewS3xConfig()
	storage := s3x.New(config)
	s3 := dao.NewS3(storage)
	adminRedis := dao.NewAdminRedis()
	daoDao := dao.New(rpcRPC, s3, adminRedis)
	mySQLDB := dao.NewMySQL()
	tdsqldb := dao.NewTDSQL()
	qaDao := qa.NewDao(mySQLDB, tdsqldb, adminRedis)
	v := dao.NewElasticSearchClient()
	segmentDao := segment.NewDao(mySQLDB, tdsqldb, v)
	releaseDao := release.NewDao(mySQLDB, tdsqldb)
	labelDao := label.NewDao(mySQLDB, tdsqldb, adminRedis, v)
	categoryDao := category.NewDao(mySQLDB, adminRedis)
	tex2sqlDB := dao.NewText2sqlDB()
	documentDao := document.NewDao(mySQLDB, tdsqldb, tex2sqlDB, adminRedis)
	databaseDao := database.NewDao(rpcRPC, tdsqldb, adminRedis)
	kbDeleteDB := dao.NewKbDeleteClient()
	retrievalRedis := dao.NewRetrievalRedis()
	kbDao := kb.NewDao(mySQLDB, tdsqldb, kbDeleteDB, adminRedis, retrievalRedis)
	userDao := user.NewDao(tdsqldb, mySQLDB, adminRedis)
	vectorDao := vector.NewDao(mySQLDB, tdsqldb)
	vectorSyncLogic := vector2.NewLogic(daoDao, documentDao, labelDao, kbDao, qaDao, segmentDao, userDao, vectorDao, categoryDao, rpcRPC)
	logic := localcache.NewLogic(documentDao, rpcRPC)
	segmentLogic := segment2.NewLogic(rpcRPC, documentDao, qaDao, segmentDao, releaseDao, databaseDao, s3, vectorSyncLogic, logic)
	financeLogic := finance.NewLogic(rpcRPC)
	llmDao := llm.NewDao(mySQLDB)
	llmLogic := llm2.NewLogic(rpcRPC, llmDao)
	qaLogic := qa2.NewLogic(labelDao, categoryDao, documentDao, qaDao, releaseDao, segmentDao, segmentLogic, financeLogic, llmLogic, vectorSyncLogic, s3, rpcRPC)
	appLogic := app.NewLogic(rpcRPC)
	labelLogic := label2.NewLogic(rpcRPC, labelDao, documentDao, appLogic)
	onedriveDao := third_doc_dao.NewOnedriveDao(tdsqldb)
	onedriveDocLogic := third_document.NewOnedriveDocLogic(rpcRPC, onedriveDao, userDao)
	third_documentLogic := third_document.NewLogic(onedriveDocLogic)
	documentLogic := document2.NewLogic(daoDao, documentDao, labelDao, segmentDao, releaseDao, qaDao, databaseDao, segmentLogic, qaLogic, labelLogic, rpcRPC, s3, llmLogic, third_documentLogic)
	kbLogic := kb2.NewLogic(databaseDao, kbDao, adminRedis, documentDao, rpcRPC, financeLogic)
	userLogic := user2.NewLogic(rpcRPC, userDao, databaseDao, kbDao, labelDao, categoryDao, adminRedis, documentLogic, qaLogic)
	databaseLogic := database2.NewLogic(databaseDao, rpcRPC, kbLogic, userLogic, releaseDao)
	releaseLogic := release2.NewLogic(rpcRPC, databaseLogic, documentLogic, kbLogic, labelLogic, qaLogic, daoDao, qaDao, segmentDao, labelDao, releaseDao)
	auditLogic := audit.NewLogic(rpcRPC, daoDao, qaDao, segmentDao, releaseDao, qaLogic, segmentLogic, documentLogic, releaseLogic, s3)
	categoryLogic := category2.NewLogic(categoryDao, qaDao, documentDao)
	taskLogic := task.NewLogic(qaLogic, documentLogic, segmentLogic, rpcRPC)
	exportDao := export.NewDao(mySQLDB)
	exportLogic := export2.NewLogic(rpcRPC, exportDao)
	mainCmdService := New(rpcRPC, daoDao, auditLogic, logic, documentLogic, qaLogic, segmentLogic, releaseLogic, kbLogic, s3, categoryLogic, userLogic, labelLogic, taskLogic, databaseLogic, exportLogic, vectorSyncLogic, databaseDao, kbDao, labelDao, financeLogic, adminRedis, llmDao, third_documentLogic, v)
	return mainCmdService
}

var (
	_wireAdminClientProxyValue                             = app_config.NewAdminClientProxy()
	_wirePlatform_managerAdminClientProxyValue             = platform_manager.NewAdminClientProxy()
	_wireLoginClientProxyValue                             = platform_manager.NewLoginClientProxy()
	_wireDirectIndexClientProxyValue                       = kb_retrieval.NewDirectIndexClientProxy()
	_wireRetrievalClientProxyValue                         = kb_retrieval.NewRetrievalClientProxy()
	_wireTaskConfigClientProxyValue                        = KEP.NewTaskConfigClientProxy()
	_wireClientValue                                       = http.NewClientProxy("lke-code-node-tdoclinker")
	_wireManagerObjClientProxyValue                        = filemanagerserver.NewManagerObjClientProxy()
	_wireEmbeddingObjClientProxyValue                      = embeddingserver.NewEmbeddingObjClientProxy()
	_wireFinanceClientProxyValue                           = finance2.NewFinanceClientProxy()
	_wireInfosecClientProxyValue                           = infosec.NewInfosecClientProxy()
	_wireShort_urlAdminClientProxyValue                    = short_url.NewAdminClientProxy()
	_wireParserObjClientProxyValue                         = web_parser_server.NewParserObjClientProxy()
	_wireNrt_file_manager_serverManagerObjClientProxyValue = nrt_file_manager_server.NewManagerObjClientProxy()
	_wireAccessManagerClientProxyValue                     = access_manager_server.NewAccessManagerClientProxy()
	_wireResource_galleryAdminClientProxyValue             = resource_gallery.NewAdminClientProxy()
	_wireVectorObjClientProxyValue                         = vector_db_manager.NewVectorObjClientProxy()
	_wireApiClientProxyValue                               = bot_data_statistics_server.NewApiClientProxy()
)

// wire.go:

var ProviderSet = wire.NewSet(dao.New, logic.ProviderSet, rpc.ProviderSet)
