// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"git.code.oa.com/trpc-go/trpc-go/http"
	"git.woa.com/adp/common/x/clientx/s3x"
	"git.woa.com/adp/kb/kb-config/internal/async"
	"git.woa.com/adp/kb/kb-config/internal/dao"
	"git.woa.com/adp/kb/kb-config/internal/dao/category"
	"git.woa.com/adp/kb/kb-config/internal/dao/database"
	"git.woa.com/adp/kb/kb-config/internal/dao/document"
	"git.woa.com/adp/kb/kb-config/internal/dao/export"
	"git.woa.com/adp/kb/kb-config/internal/dao/kb"
	"git.woa.com/adp/kb/kb-config/internal/dao/label"
	"git.woa.com/adp/kb/kb-config/internal/dao/llm"
	"git.woa.com/adp/kb/kb-config/internal/dao/qa"
	"git.woa.com/adp/kb/kb-config/internal/dao/release"
	"git.woa.com/adp/kb/kb-config/internal/dao/segment"
	"git.woa.com/adp/kb/kb-config/internal/dao/third_document"
	"git.woa.com/adp/kb/kb-config/internal/dao/user"
	"git.woa.com/adp/kb/kb-config/internal/dao/vector"
	"git.woa.com/adp/kb/kb-config/internal/logic/app"
	"git.woa.com/adp/kb/kb-config/internal/logic/audit"
	category2 "git.woa.com/adp/kb/kb-config/internal/logic/category"
	database2 "git.woa.com/adp/kb/kb-config/internal/logic/database"
	document2 "git.woa.com/adp/kb/kb-config/internal/logic/document"
	export2 "git.woa.com/adp/kb/kb-config/internal/logic/export"
	"git.woa.com/adp/kb/kb-config/internal/logic/finance"
	kb2 "git.woa.com/adp/kb/kb-config/internal/logic/kb"
	"git.woa.com/adp/kb/kb-config/internal/logic/kb_package"
	label2 "git.woa.com/adp/kb/kb-config/internal/logic/label"
	llm2 "git.woa.com/adp/kb/kb-config/internal/logic/llm"
	"git.woa.com/adp/kb/kb-config/internal/logic/localcache"
	qa2 "git.woa.com/adp/kb/kb-config/internal/logic/qa"
	release2 "git.woa.com/adp/kb/kb-config/internal/logic/release"
	"git.woa.com/adp/kb/kb-config/internal/logic/search"
	segment2 "git.woa.com/adp/kb/kb-config/internal/logic/segment"
	"git.woa.com/adp/kb/kb-config/internal/logic/task"
	"git.woa.com/adp/kb/kb-config/internal/logic/third_document"
	user2 "git.woa.com/adp/kb/kb-config/internal/logic/user"
	vector2 "git.woa.com/adp/kb/kb-config/internal/logic/vector"
	"git.woa.com/adp/kb/kb-config/internal/rpc"
	"git.woa.com/adp/kb/kb-config/internal/service"
	"git.woa.com/adp/kb/kb-config/internal/service/api"
	"git.woa.com/adp/pb-go/app/app_config"
	"git.woa.com/adp/pb-go/kb/kb_retrieval"
	"git.woa.com/adp/pb-go/kb/parse_engine/file_manager_server"
	"git.woa.com/adp/pb-go/kb/parse_engine/kb_parse_router"
	"git.woa.com/adp/pb-go/platform/platform_charger"
	"git.woa.com/adp/pb-go/platform/platform_manager"
	"git.woa.com/adp/pb-go/platform/platform_metrology"
	"git.woa.com/adp/pb-go/resource_gallery/resource_gallery"
	"git.woa.com/dialogue-platform/lke_proto/pb-protocol/KEP"
	"git.woa.com/dialogue-platform/proto/pb-stub/access-manager-server"
	"git.woa.com/dialogue-platform/proto/pb-stub/embedding_server"
	"git.woa.com/dialogue-platform/proto/pb-stub/vector_db_manager"
	"git.woa.com/dialogue-platform/proto/pb-stub/web-parser-server"
	"git.woa.com/ivy/protobuf/trpc-go/qbot/qbot/infosec"
	"git.woa.com/ivy/protobuf/trpc-go/qbot/qbot/short_url"
)

import (
	_ "git.woa.com/adp/kb/kb-config/internal/dao/segment"
)

// Injectors from wire.go:

func newService() *service.Service {
	adminClientProxy := _wireAdminClientProxyValue
	apiClientProxy := _wireApiClientProxyValue
	platform_managerAdminClientProxy := _wirePlatform_managerAdminClientProxyValue
	loginClientProxy := _wireLoginClientProxyValue
	platform_managerApiClientProxy := _wirePlatform_managerApiClientProxyValue
	directIndexClientProxy := _wireDirectIndexClientProxyValue
	retrievalClientProxy := _wireRetrievalClientProxyValue
	taskConfigClientProxy := _wireTaskConfigClientProxyValue
	tDocLinkerHTTP := _wireClientValue
	managerObjClientProxy := _wireManagerObjClientProxyValue
	embeddingObjClientProxy := _wireEmbeddingObjClientProxyValue
	financeClientProxy := _wireFinanceClientProxyValue
	infosecClientProxy := _wireInfosecClientProxyValue
	short_urlAdminClientProxy := _wireShort_urlAdminClientProxyValue
	parserObjClientProxy := _wireParserObjClientProxyValue
	accessManagerClientProxy := _wireAccessManagerClientProxyValue
	resource_galleryAdminClientProxy := _wireResource_galleryAdminClientProxyValue
	client := rpc.NewOpenAiClient()
	vectorObjClientProxy := _wireVectorObjClientProxyValue
	platform_metrologyApiClientProxy := _wirePlatform_metrologyApiClientProxyValue
	parseRouterClientProxy := _wireParseRouterClientProxyValue
	rpcRPC := rpc.New(adminClientProxy, apiClientProxy, platform_managerAdminClientProxy, loginClientProxy, platform_managerApiClientProxy, directIndexClientProxy, retrievalClientProxy, taskConfigClientProxy, tDocLinkerHTTP, managerObjClientProxy, embeddingObjClientProxy, financeClientProxy, infosecClientProxy, short_urlAdminClientProxy, parserObjClientProxy, accessManagerClientProxy, resource_galleryAdminClientProxy, client, vectorObjClientProxy, platform_metrologyApiClientProxy, parseRouterClientProxy)
	config := dao.NewS3xConfig()
	storage := s3x.New(config)
	s3 := dao.NewS3(storage)
	adminRedis := dao.NewAdminRedis()
	daoDao := dao.New(rpcRPC, s3, adminRedis)
	mySQLDB := dao.NewMySQL()
	tdsqldb := dao.NewTDSQL()
	qaDao := qa.NewDao(mySQLDB, tdsqldb, adminRedis)
	esClient := dao.NewElasticSearchClient()
	segmentDao := segment.NewDao(mySQLDB, tdsqldb, esClient)
	releaseDao := release.NewDao(mySQLDB, tdsqldb)
	labelDao := label.NewDao(mySQLDB, tdsqldb, adminRedis, esClient)
	categoryDao := category.NewDao(mySQLDB, adminRedis)
	tex2sqlDB := dao.NewText2sqlDB()
	documentDao := document.NewDao(mySQLDB, tdsqldb, tex2sqlDB, adminRedis)
	databaseDao := database.NewDao(rpcRPC, tdsqldb, adminRedis)
	kbDeleteDB := dao.NewKbDeleteClient()
	retrievalRedis := dao.NewRetrievalRedis()
	kbDao := kb.NewDao(mySQLDB, tdsqldb, kbDeleteDB, adminRedis, retrievalRedis)
	userDao := user.NewDao(tdsqldb, mySQLDB, adminRedis)
	vectorDao := vector.NewDao(mySQLDB, tdsqldb)
	vectorSyncLogic := vector2.NewLogic(daoDao, documentDao, labelDao, kbDao, qaDao, segmentDao, userDao, vectorDao, categoryDao, rpcRPC)
	logic := localcache.NewLogic(documentDao, rpcRPC)
	segmentLogic := segment2.NewLogic(rpcRPC, documentDao, qaDao, segmentDao, releaseDao, databaseDao, s3, vectorSyncLogic, logic)
	financeLogic := finance.NewLogic(rpcRPC)
	llmDao := llm.NewDao(mySQLDB)
	llmLogic := llm2.NewLogic(rpcRPC, llmDao)
	qaLogic := qa2.NewLogic(labelDao, categoryDao, documentDao, qaDao, releaseDao, segmentDao, segmentLogic, financeLogic, llmLogic, vectorSyncLogic, s3, rpcRPC)
	appLogic := app.NewLogic(rpcRPC)
	labelLogic := label2.NewLogic(rpcRPC, labelDao, documentDao, appLogic)
	onedriveDao := third_doc_dao.NewOnedriveDao(tdsqldb)
	onedriveDocLogic := third_document.NewOnedriveDocLogic(rpcRPC, onedriveDao, userDao)
	third_documentLogic := third_document.NewLogic(onedriveDocLogic)
	documentLogic := document2.NewLogic(daoDao, documentDao, labelDao, segmentDao, releaseDao, qaDao, databaseDao, segmentLogic, qaLogic, labelLogic, rpcRPC, s3, kbDao, categoryDao, llmLogic, third_documentLogic, financeLogic, userDao)
	userLogic := user2.NewLogic(rpcRPC, userDao, databaseDao, kbDao, labelDao, categoryDao, adminRedis, documentLogic, qaLogic)
	categoryLogic := category2.NewLogic(categoryDao, qaDao, documentDao)
	kbLogic := kb2.NewLogic(databaseDao, kbDao, adminRedis, documentDao, rpcRPC, financeLogic, userLogic, documentLogic, qaLogic, logic, categoryLogic)
	databaseLogic := database2.NewLogic(databaseDao, rpcRPC, kbLogic, userLogic, releaseDao)
	releaseLogic := release2.NewLogic(rpcRPC, databaseLogic, documentLogic, kbLogic, labelLogic, qaLogic, daoDao, qaDao, segmentDao, labelDao, releaseDao, userLogic)
	auditLogic := audit.NewLogic(rpcRPC, daoDao, qaDao, segmentDao, releaseDao, qaLogic, segmentLogic, documentLogic, releaseLogic, s3, financeLogic)
	taskLogic := task.NewLogic(qaLogic, documentLogic, segmentLogic, rpcRPC)
	exportDao := export.NewDao(mySQLDB)
	exportLogic := export2.NewLogic(rpcRPC, exportDao)
	kb_packageLogic := kb_package.NewLogic(rpcRPC, kbDao, labelDao, documentLogic, s3, logic)
	serviceService := service.New(rpcRPC, daoDao, auditLogic, logic, documentLogic, qaLogic, segmentLogic, releaseLogic, kbLogic, s3, categoryLogic, userLogic, labelLogic, taskLogic, databaseLogic, exportLogic, vectorSyncLogic, databaseDao, kbDao, labelDao, financeLogic, adminRedis, llmDao, third_documentLogic, kb_packageLogic)
	return serviceService
}

var (
	_wireAdminClientProxyValue                 = app_config.NewAdminClientProxy()
	_wireApiClientProxyValue                   = app_config.NewApiClientProxy()
	_wirePlatform_managerAdminClientProxyValue = platform_manager.NewAdminClientProxy()
	_wireLoginClientProxyValue                 = platform_manager.NewLoginClientProxy()
	_wirePlatform_managerApiClientProxyValue   = platform_manager.NewApiClientProxy()
	_wireDirectIndexClientProxyValue           = kb_retrieval.NewDirectIndexClientProxy()
	_wireRetrievalClientProxyValue             = kb_retrieval.NewRetrievalClientProxy()
	_wireTaskConfigClientProxyValue            = KEP.NewTaskConfigClientProxy()
	_wireClientValue                           = http.NewClientProxy("lke-code-node-tdoclinker")
	_wireManagerObjClientProxyValue            = file_manager_server.NewManagerObjClientProxy()
	_wireEmbeddingObjClientProxyValue          = embeddingserver.NewEmbeddingObjClientProxy()
	_wireFinanceClientProxyValue               = platform_charger.NewFinanceClientProxy()
	_wireInfosecClientProxyValue               = infosec.NewInfosecClientProxy()
	_wireShort_urlAdminClientProxyValue        = short_url.NewAdminClientProxy()
	_wireParserObjClientProxyValue             = web_parser_server.NewParserObjClientProxy()
	_wireAccessManagerClientProxyValue         = access_manager_server.NewAccessManagerClientProxy()
	_wireResource_galleryAdminClientProxyValue = resource_gallery.NewAdminClientProxy()
	_wireVectorObjClientProxyValue             = vector_db_manager.NewVectorObjClientProxy()
	_wirePlatform_metrologyApiClientProxyValue = platform_metrology.NewApiClientProxy()
	_wireParseRouterClientProxyValue           = kb_parse_router.NewParseRouterClientProxy()
)

func newAPI() *api.Service {
	adminClientProxy := _wireAdminClientProxyValue
	apiClientProxy := _wireApiClientProxyValue
	platform_managerAdminClientProxy := _wirePlatform_managerAdminClientProxyValue
	loginClientProxy := _wireLoginClientProxyValue
	platform_managerApiClientProxy := _wirePlatform_managerApiClientProxyValue
	directIndexClientProxy := _wireDirectIndexClientProxyValue
	retrievalClientProxy := _wireRetrievalClientProxyValue
	taskConfigClientProxy := _wireTaskConfigClientProxyValue
	tDocLinkerHTTP := _wireClientValue
	managerObjClientProxy := _wireManagerObjClientProxyValue
	embeddingObjClientProxy := _wireEmbeddingObjClientProxyValue
	financeClientProxy := _wireFinanceClientProxyValue
	infosecClientProxy := _wireInfosecClientProxyValue
	short_urlAdminClientProxy := _wireShort_urlAdminClientProxyValue
	parserObjClientProxy := _wireParserObjClientProxyValue
	accessManagerClientProxy := _wireAccessManagerClientProxyValue
	resource_galleryAdminClientProxy := _wireResource_galleryAdminClientProxyValue
	client := rpc.NewOpenAiClient()
	vectorObjClientProxy := _wireVectorObjClientProxyValue
	platform_metrologyApiClientProxy := _wirePlatform_metrologyApiClientProxyValue
	parseRouterClientProxy := _wireParseRouterClientProxyValue
	rpcRPC := rpc.New(adminClientProxy, apiClientProxy, platform_managerAdminClientProxy, loginClientProxy, platform_managerApiClientProxy, directIndexClientProxy, retrievalClientProxy, taskConfigClientProxy, tDocLinkerHTTP, managerObjClientProxy, embeddingObjClientProxy, financeClientProxy, infosecClientProxy, short_urlAdminClientProxy, parserObjClientProxy, accessManagerClientProxy, resource_galleryAdminClientProxy, client, vectorObjClientProxy, platform_metrologyApiClientProxy, parseRouterClientProxy)
	config := dao.NewS3xConfig()
	storage := s3x.New(config)
	s3 := dao.NewS3(storage)
	adminRedis := dao.NewAdminRedis()
	daoDao := dao.New(rpcRPC, s3, adminRedis)
	mySQLDB := dao.NewMySQL()
	tdsqldb := dao.NewTDSQL()
	qaDao := qa.NewDao(mySQLDB, tdsqldb, adminRedis)
	esClient := dao.NewElasticSearchClient()
	segmentDao := segment.NewDao(mySQLDB, tdsqldb, esClient)
	releaseDao := release.NewDao(mySQLDB, tdsqldb)
	labelDao := label.NewDao(mySQLDB, tdsqldb, adminRedis, esClient)
	categoryDao := category.NewDao(mySQLDB, adminRedis)
	tex2sqlDB := dao.NewText2sqlDB()
	documentDao := document.NewDao(mySQLDB, tdsqldb, tex2sqlDB, adminRedis)
	databaseDao := database.NewDao(rpcRPC, tdsqldb, adminRedis)
	kbDeleteDB := dao.NewKbDeleteClient()
	retrievalRedis := dao.NewRetrievalRedis()
	kbDao := kb.NewDao(mySQLDB, tdsqldb, kbDeleteDB, adminRedis, retrievalRedis)
	userDao := user.NewDao(tdsqldb, mySQLDB, adminRedis)
	vectorDao := vector.NewDao(mySQLDB, tdsqldb)
	vectorSyncLogic := vector2.NewLogic(daoDao, documentDao, labelDao, kbDao, qaDao, segmentDao, userDao, vectorDao, categoryDao, rpcRPC)
	logic := localcache.NewLogic(documentDao, rpcRPC)
	segmentLogic := segment2.NewLogic(rpcRPC, documentDao, qaDao, segmentDao, releaseDao, databaseDao, s3, vectorSyncLogic, logic)
	financeLogic := finance.NewLogic(rpcRPC)
	llmDao := llm.NewDao(mySQLDB)
	llmLogic := llm2.NewLogic(rpcRPC, llmDao)
	qaLogic := qa2.NewLogic(labelDao, categoryDao, documentDao, qaDao, releaseDao, segmentDao, segmentLogic, financeLogic, llmLogic, vectorSyncLogic, s3, rpcRPC)
	appLogic := app.NewLogic(rpcRPC)
	labelLogic := label2.NewLogic(rpcRPC, labelDao, documentDao, appLogic)
	onedriveDao := third_doc_dao.NewOnedriveDao(tdsqldb)
	onedriveDocLogic := third_document.NewOnedriveDocLogic(rpcRPC, onedriveDao, userDao)
	third_documentLogic := third_document.NewLogic(onedriveDocLogic)
	documentLogic := document2.NewLogic(daoDao, documentDao, labelDao, segmentDao, releaseDao, qaDao, databaseDao, segmentLogic, qaLogic, labelLogic, rpcRPC, s3, kbDao, categoryDao, llmLogic, third_documentLogic, financeLogic, userDao)
	userLogic := user2.NewLogic(rpcRPC, userDao, databaseDao, kbDao, labelDao, categoryDao, adminRedis, documentLogic, qaLogic)
	categoryLogic := category2.NewLogic(categoryDao, qaDao, documentDao)
	kbLogic := kb2.NewLogic(databaseDao, kbDao, adminRedis, documentDao, rpcRPC, financeLogic, userLogic, documentLogic, qaLogic, logic, categoryLogic)
	databaseLogic := database2.NewLogic(databaseDao, rpcRPC, kbLogic, userLogic, releaseDao)
	releaseLogic := release2.NewLogic(rpcRPC, databaseLogic, documentLogic, kbLogic, labelLogic, qaLogic, daoDao, qaDao, segmentDao, labelDao, releaseDao, userLogic)
	auditLogic := audit.NewLogic(rpcRPC, daoDao, qaDao, segmentDao, releaseDao, qaLogic, segmentLogic, documentLogic, releaseLogic, s3, financeLogic)
	taskLogic := task.NewLogic(qaLogic, documentLogic, segmentLogic, rpcRPC)
	exportDao := export.NewDao(mySQLDB)
	exportLogic := export2.NewLogic(rpcRPC, exportDao)
	kb_packageLogic := kb_package.NewLogic(rpcRPC, kbDao, labelDao, documentLogic, s3, logic)
	serviceService := service.New(rpcRPC, daoDao, auditLogic, logic, documentLogic, qaLogic, segmentLogic, releaseLogic, kbLogic, s3, categoryLogic, userLogic, labelLogic, taskLogic, databaseLogic, exportLogic, vectorSyncLogic, databaseDao, kbDao, labelDao, financeLogic, adminRedis, llmDao, third_documentLogic, kb_packageLogic)
	searchLogic := search.NewLogic(documentDao, kbDao, releaseDao, logic)
	apiService := api.New(serviceService, daoDao, rpcRPC, auditLogic, documentLogic, qaLogic, s3, logic, segmentLogic, releaseLogic, searchLogic, userLogic, categoryLogic, databaseLogic, databaseDao, labelDao, kbLogic, labelLogic, taskLogic, kbDao, releaseDao, qaDao, financeLogic, kb_packageLogic)
	return apiService
}

func initAsync() error {
	adminClientProxy := _wireAdminClientProxyValue
	apiClientProxy := _wireApiClientProxyValue
	platform_managerAdminClientProxy := _wirePlatform_managerAdminClientProxyValue
	loginClientProxy := _wireLoginClientProxyValue
	platform_managerApiClientProxy := _wirePlatform_managerApiClientProxyValue
	directIndexClientProxy := _wireDirectIndexClientProxyValue
	retrievalClientProxy := _wireRetrievalClientProxyValue
	taskConfigClientProxy := _wireTaskConfigClientProxyValue
	tDocLinkerHTTP := _wireClientValue
	managerObjClientProxy := _wireManagerObjClientProxyValue
	embeddingObjClientProxy := _wireEmbeddingObjClientProxyValue
	financeClientProxy := _wireFinanceClientProxyValue
	infosecClientProxy := _wireInfosecClientProxyValue
	short_urlAdminClientProxy := _wireShort_urlAdminClientProxyValue
	parserObjClientProxy := _wireParserObjClientProxyValue
	accessManagerClientProxy := _wireAccessManagerClientProxyValue
	resource_galleryAdminClientProxy := _wireResource_galleryAdminClientProxyValue
	client := rpc.NewOpenAiClient()
	vectorObjClientProxy := _wireVectorObjClientProxyValue
	platform_metrologyApiClientProxy := _wirePlatform_metrologyApiClientProxyValue
	parseRouterClientProxy := _wireParseRouterClientProxyValue
	rpcRPC := rpc.New(adminClientProxy, apiClientProxy, platform_managerAdminClientProxy, loginClientProxy, platform_managerApiClientProxy, directIndexClientProxy, retrievalClientProxy, taskConfigClientProxy, tDocLinkerHTTP, managerObjClientProxy, embeddingObjClientProxy, financeClientProxy, infosecClientProxy, short_urlAdminClientProxy, parserObjClientProxy, accessManagerClientProxy, resource_galleryAdminClientProxy, client, vectorObjClientProxy, platform_metrologyApiClientProxy, parseRouterClientProxy)
	adminRedis := dao.NewAdminRedis()
	mySQLClient := dao.NewMySQLClient()
	tdsqldb := dao.NewTDSQL()
	config := dao.NewS3xConfig()
	storage := s3x.New(config)
	s3 := dao.NewS3(storage)
	daoDao := dao.New(rpcRPC, s3, adminRedis)
	mySQLDB := dao.NewMySQL()
	kbDeleteDB := dao.NewKbDeleteClient()
	retrievalRedis := dao.NewRetrievalRedis()
	kbDao := kb.NewDao(mySQLDB, tdsqldb, kbDeleteDB, adminRedis, retrievalRedis)
	qaDao := qa.NewDao(mySQLDB, tdsqldb, adminRedis)
	esClient := dao.NewElasticSearchClient()
	segmentDao := segment.NewDao(mySQLDB, tdsqldb, esClient)
	releaseDao := release.NewDao(mySQLDB, tdsqldb)
	labelDao := label.NewDao(mySQLDB, tdsqldb, adminRedis, esClient)
	categoryDao := category.NewDao(mySQLDB, adminRedis)
	tex2sqlDB := dao.NewText2sqlDB()
	documentDao := document.NewDao(mySQLDB, tdsqldb, tex2sqlDB, adminRedis)
	databaseDao := database.NewDao(rpcRPC, tdsqldb, adminRedis)
	userDao := user.NewDao(tdsqldb, mySQLDB, adminRedis)
	vectorDao := vector.NewDao(mySQLDB, tdsqldb)
	vectorSyncLogic := vector2.NewLogic(daoDao, documentDao, labelDao, kbDao, qaDao, segmentDao, userDao, vectorDao, categoryDao, rpcRPC)
	logic := localcache.NewLogic(documentDao, rpcRPC)
	segmentLogic := segment2.NewLogic(rpcRPC, documentDao, qaDao, segmentDao, releaseDao, databaseDao, s3, vectorSyncLogic, logic)
	financeLogic := finance.NewLogic(rpcRPC)
	llmDao := llm.NewDao(mySQLDB)
	llmLogic := llm2.NewLogic(rpcRPC, llmDao)
	qaLogic := qa2.NewLogic(labelDao, categoryDao, documentDao, qaDao, releaseDao, segmentDao, segmentLogic, financeLogic, llmLogic, vectorSyncLogic, s3, rpcRPC)
	appLogic := app.NewLogic(rpcRPC)
	labelLogic := label2.NewLogic(rpcRPC, labelDao, documentDao, appLogic)
	onedriveDao := third_doc_dao.NewOnedriveDao(tdsqldb)
	onedriveDocLogic := third_document.NewOnedriveDocLogic(rpcRPC, onedriveDao, userDao)
	third_documentLogic := third_document.NewLogic(onedriveDocLogic)
	documentLogic := document2.NewLogic(daoDao, documentDao, labelDao, segmentDao, releaseDao, qaDao, databaseDao, segmentLogic, qaLogic, labelLogic, rpcRPC, s3, kbDao, categoryDao, llmLogic, third_documentLogic, financeLogic, userDao)
	userLogic := user2.NewLogic(rpcRPC, userDao, databaseDao, kbDao, labelDao, categoryDao, adminRedis, documentLogic, qaLogic)
	categoryLogic := category2.NewLogic(categoryDao, qaDao, documentDao)
	kbLogic := kb2.NewLogic(databaseDao, kbDao, adminRedis, documentDao, rpcRPC, financeLogic, userLogic, documentLogic, qaLogic, logic, categoryLogic)
	databaseLogic := database2.NewLogic(databaseDao, rpcRPC, kbLogic, userLogic, releaseDao)
	releaseLogic := release2.NewLogic(rpcRPC, databaseLogic, documentLogic, kbLogic, labelLogic, qaLogic, daoDao, qaDao, segmentDao, labelDao, releaseDao, userLogic)
	auditLogic := audit.NewLogic(rpcRPC, daoDao, qaDao, segmentDao, releaseDao, qaLogic, segmentLogic, documentLogic, releaseLogic, s3, financeLogic)
	exportDao := export.NewDao(mySQLDB)
	exportLogic := export2.NewLogic(rpcRPC, exportDao)
	taskLogic := task.NewLogic(qaLogic, documentLogic, segmentLogic, rpcRPC)
	kb_packageLogic := kb_package.NewLogic(rpcRPC, kbDao, labelDao, documentLogic, s3, logic)
	error2 := async.Init(rpcRPC, adminRedis, mySQLClient, tdsqldb, daoDao, kbDao, auditLogic, labelDao, userLogic, documentLogic, qaLogic, releaseLogic, s3, segmentLogic, categoryLogic, databaseLogic, exportLogic, taskLogic, labelLogic, kbLogic, databaseDao, financeLogic, llmLogic, third_documentLogic, kb_packageLogic)
	return error2
}

func newRPC() *rpc.RPC {
	adminClientProxy := _wireAdminClientProxyValue
	apiClientProxy := _wireApiClientProxyValue
	platform_managerAdminClientProxy := _wirePlatform_managerAdminClientProxyValue
	loginClientProxy := _wireLoginClientProxyValue
	platform_managerApiClientProxy := _wirePlatform_managerApiClientProxyValue
	directIndexClientProxy := _wireDirectIndexClientProxyValue
	retrievalClientProxy := _wireRetrievalClientProxyValue
	taskConfigClientProxy := _wireTaskConfigClientProxyValue
	tDocLinkerHTTP := _wireClientValue
	managerObjClientProxy := _wireManagerObjClientProxyValue
	embeddingObjClientProxy := _wireEmbeddingObjClientProxyValue
	financeClientProxy := _wireFinanceClientProxyValue
	infosecClientProxy := _wireInfosecClientProxyValue
	short_urlAdminClientProxy := _wireShort_urlAdminClientProxyValue
	parserObjClientProxy := _wireParserObjClientProxyValue
	accessManagerClientProxy := _wireAccessManagerClientProxyValue
	resource_galleryAdminClientProxy := _wireResource_galleryAdminClientProxyValue
	client := rpc.NewOpenAiClient()
	vectorObjClientProxy := _wireVectorObjClientProxyValue
	platform_metrologyApiClientProxy := _wirePlatform_metrologyApiClientProxyValue
	parseRouterClientProxy := _wireParseRouterClientProxyValue
	rpcRPC := rpc.New(adminClientProxy, apiClientProxy, platform_managerAdminClientProxy, loginClientProxy, platform_managerApiClientProxy, directIndexClientProxy, retrievalClientProxy, taskConfigClientProxy, tDocLinkerHTTP, managerObjClientProxy, embeddingObjClientProxy, financeClientProxy, infosecClientProxy, short_urlAdminClientProxy, parserObjClientProxy, accessManagerClientProxy, resource_galleryAdminClientProxy, client, vectorObjClientProxy, platform_metrologyApiClientProxy, parseRouterClientProxy)
	return rpcRPC
}
