package errs

import (
	"errors"

	"git.code.oa.com/trpc-go/trpc-go/errs"
	"git.woa.com/adp/common/x/errx"

	"git.woa.com/adp/kb/kb-config/pkg/i18nkey"
)

const (
	SystemIntegratorNameQiDian = "企点" // 集成商表t_system_integrator中企点的名称
)

// ErrMap 集成商定制错误信息映射表 集成商id -> 通用错误信息 -> 定制错误信息
var ErrMap = map[string]map[error]error{
	SystemIntegratorNameQiDian: {
		ErrOverCharacterSizeLimit: ErrOverCharacterSizeLimit4QiDian,
	},
}

// Err2KeyMap 错误信息映射表 error -> i18n_key
var Err2KeyMap = map[error]string{
	ErrOverCharacterSizeLimit:        i18nkey.KeyOverCharacterSizeLimit,
	ErrOverCharacterSizeLimit4QiDian: i18nkey.KeyOverCharacterSizeLimit4QiDian,
	ErrBotOverCharacterSizeLimit:     i18nkey.KeyBotOverCharacterSizeLimit,
	ErrCorpNotFound:                  i18nkey.KeyCorpNotFound,
	ErrSystem:                        i18nkey.KeySystemError,
}

// errors 服务内部定义的错误要暴露出去，调用方需要引用它来判断错误类型
var (
	ErrCodeExcelContent               = errx.Newf(450081, "ErrCodeExcelContent")
	ErrCodeAnswerTooLong              = errx.Newf(400035, "ErrCodeAnswerTooLong")
	ErrCodeAnswerTooShort             = errx.Newf(400031, "ErrCodeAnswerTooShort")
	ErrCodeQuestionTooLong            = errx.Newf(400034, "ErrCodeQuestionTooLong")
	ErrCodeQuestionTooShort           = errx.Newf(400030, "ErrCodeQuestionTooShort")
	ErrCodeCateNameTooLong            = errx.Newf(400032, "ErrCodeCateNameTooLong")
	ErrCodeCateNameTooShort           = errx.Newf(400029, "ErrCodeCateNameTooShort")
	ErrCodeImportLengthExceedLimit    = errx.Newf(450083, "ErrCodeImportLengthExceedLimit")
	ErrCodeCateCountExceed            = errx.Newf(450084, "ErrCodeCateCountExceed")
	ErrCodeUserHasJoinCorp            = errx.Newf(450115, "ErrCodeUserHasJoinCorp")
	ErrCodeExcelNumTooFew             = errx.Newf(400037, "ErrCodeExcelNumTooFew")
	ErrCodeExcelNumTooMany            = errx.Newf(400038, "ErrCodeExcelNumTooMany")
	ErrCodeSimilarQuestionExceedLimit = errx.Newf(400039, "ErrCodeSimilarQuestionExceedLimit")
	ErrCodeSimilarQuestionRepeated    = errx.Newf(400040, "ErrCodeSimilarQuestionRepeated")
	ErrCodeAIConf                     = errx.Newf(450085, "ErrCodeAIConf")

	ErrAlreadyLocked                    = errx.Newf(400028, "ErrAlreadyLocked")
	ErrRobotInitFail                    = errx.Newf(400033, "ErrRobotInitFail")
	ErrUnknownSplitModel                = errx.Newf(400036, "ErrUnknownSplitModel")
	ErrCorpNotFound                     = errx.Newf(400037, "ErrCorpNotFound")
	ErrUnknownSplitProc                 = errx.Newf(400037, "ErrUnknownSplitProc")
	ErrDocNotFound                      = errx.Newf(450001, "ErrDocNotFound")
	ErrPermissionDenied                 = errx.Newf(450002, "ErrPermissionDenied")
	ErrDocStatusNotAllowReCreateQA      = errx.Newf(450003, "ErrDocStatusNotAllowReCreateQA")
	ErrUserNotFound                     = errx.Newf(450004, "ErrUserNotFound")
	ErrStaffNotFound                    = errx.Newf(450005, "ErrStaffNotFound")
	ErrUserIsInValid                    = errx.Newf(450005, "ErrUserIsInValid")
	ErrSessionNotFound                  = errx.Newf(450006, "ErrSessionNotFound")
	ErrSmsSendFailed                    = errx.Newf(450007, "ErrSmsSendFailed")
	ErrVerifyCode                       = errx.Newf(450008, "ErrVerifyCode")
	ErrSmsSendLimit                     = errx.Newf(450009, "ErrSmsSendLimit")
	ErrVerifyFailedTooManyTimes         = errx.Newf(450010, "ErrVerifyFailedTooManyTimes")
	ErrRobotNotFound                    = errx.Newf(450011, "ErrAppNotFound")
	ErrCateNotFound                     = errx.Newf(450012, "ErrCateNotFound")
	ErrQANotFound                       = errx.Newf(450013, "ErrQANotFound")
	ErrQAIsDeleted                      = errx.Newf(450014, "ErrQAIsDeleted")
	ErrLockTaskFail                     = errx.Newf(450015, "ErrLockTaskFail")
	ErrUnSupportFileType                = errx.Newf(450016, "ErrUnSupportFileType")
	ErrReleaseFail                      = errx.Newf(450017, "ErrReleaseFail")
	ErrQASimilarNotFound                = errx.Newf(450018, "ErrQASimilarNotFound")
	ErrDocHasDeleted                    = errx.Newf(450019, "ErrDocHasDeleted")
	ErrDocExist                         = errx.Newf(450020, "ErrDocExist")
	ErrForbidRefer                      = errx.Newf(450022, "ErrForbidRefer")
	ErrStatusSuccess                    = errx.Newf(450022, "ErrStatusSuccess")
	ErrDocIsRelease                     = errx.Newf(450023, "ErrDocIsRelease")
	ErrSystem                           = errx.Newf(450024, "ErrSystem")
	ErrReleaseNotFound                  = errx.Newf(450025, "ErrReleaseNotFound")
	ErrNoReleaseQA                      = errx.Newf(450027, "ErrNoReleaseQA")
	ErrSegmentNotFound                  = errx.Newf(450038, "ErrSegmentNotFound")
	ErrHasInAuditCorp                   = errx.Newf(450040, "ErrHasInAuditCorp")
	ErrTaskNotFound                     = errx.Newf(450040, "ErrTaskNotFound")
	ErrDocForbidDelete                  = errx.Newf(450041, "ErrDocForbidDelete")
	ErrTaskIsNotInit                    = errx.Newf(450041, "ErrTaskIsNotInit")
	ErrSegmentIsEmpty                   = errx.Newf(450042, "ErrSegmentIsEmpty")
	ErrTaskIsStop                       = errx.Newf(450042, "ErrTaskIsStop")
	ErrQAIsPendingRelease               = errx.Newf(450043, "ErrQAIsPendingRelease")
	ErrExcelIsEmpty                     = errx.Newf(450044, "ErrExcelIsEmpty")
	ErrDocTypeForIndex                  = errx.Newf(450045, "ErrDocTypeForIndex")
	ErrTaskMaxTryTimes                  = errx.Newf(450045, "ErrTaskMaxTryTimes")
	ErrCorpInValid                      = errx.Newf(450046, "ErrCorpInValid")
	ErrSegmentAlreadyExist              = errx.Newf(450046, "ErrSegmentAlreadyExist")
	ErrReleaseIsNotPending              = errx.Newf(450047, "ErrReleaseIsNotPending")
	ErrSegmentQAAlreadyExist            = errx.Newf(450047, "ErrSegmentQAAlreadyExist")
	ErrDocTplNotFound                   = errx.Newf(450049, "ErrDocTplNotFound")
	ErrDoingRelease                     = errx.Newf(450050, "ErrDoingRelease")
	ErrExcelHead                        = errx.Newf(450051, "ErrExcelHead")
	ErrQANotModifyFound                 = errx.Newf(450052, "ErrQANotModifyFound")
	ErrGetTemplateFail                  = errx.Newf(450053, "ErrGetTemplateFail")
	ErrGetDocListFail                   = errx.Newf(450054, "ErrGetDocListFail")
	ErrUserWaitAudit                    = errx.Newf(450055, "ErrUserWaitAudit")
	ErrLoginTimesLimit                  = errx.Newf(450056, "ErrLoginTimesLimit")
	ErrAlreadyJoinedCorp                = errx.Newf(450057, "ErrAlreadyJoinedCorp")
	ErrParams                           = errx.Newf(450057, "ErrParams")
	ErrSameDocUploading                 = errx.Newf(450058, "ErrSameDocUploading")
	ErrRepeatCorpName                   = errx.Newf(450059, "ErrRepeatCorpName")
	ErrSegmentNotForIndex               = errx.Newf(450059, "ErrSegmentNotForIndex")
	ErrReleaseType                      = errx.Newf(450060, "ErrReleaseType")
	ErrVerifyCodeNotFound               = errx.Newf(450061, "ErrVerifyCodeNotFound")
	ErrReferDocFail                     = errx.Newf(450062, "ErrReferDocFail")
	ErrFetchURLFail                     = errx.Newf(450063, "ErrFetchURLFail")
	ErrInvalidURL                       = errx.Newf(450064, "ErrInvalidURL")
	ErrInvalidFileName                  = errx.Newf(450065, "ErrInvalidFileName")
	ErrInvalidAuditSource               = errx.Newf(450066, "ErrInvalidAuditSource")
	ErrReleaseQANotFound                = errx.Newf(450067, "ErrReleaseQANotFound")
	ErrUnknownSplitConfig               = errx.Newf(450076, "ErrUnknownSplitConfig")
	ErrUnknownMergerType                = errx.Newf(450077, "ErrUnknownMergerType")
	ErrFetchURLTooBig                   = errx.Newf(450078, "ErrFetchURLTooBig")
	ErrUnknownMiniChunkType             = errx.Newf(450079, "ErrUnknownMiniChunkType")
	ErrRobotInAudit                     = errx.Newf(450080, "ErrRobotInAudit")
	ErrExcelContent                     = errx.Newf(450081, "ErrExcelContent")
	ErrCateCountExceed                  = errx.Newf(450084, "ErrCateCountExceed")
	ErrExportQA                         = errx.Newf(450085, "ErrExportQA")
	ErrExportQATooMany                  = errx.Newf(450086, "ErrExportQATooMany")
	ErrExportQATaskTooMany              = errx.Newf(450087, "ErrExportQATaskTooMany")
	ErrRobotQuotaNotEnough              = errx.Newf(450087, "ErrRobotQuotaNotEnough")
	ErrAuditFlagNotFound                = errx.Newf(450088, "ErrAuditFlagNotFound")
	ErrAuditFlagNotFount                = errx.Newf(450088, "ErrAuditFlagNotFount")
	ErrUserHasNoCorp                    = errx.Newf(450089, "ErrUserHasNoCorp")
	ErrCateDepthExceed                  = errx.Newf(450090, "ErrCateDepthExceed")
	ErrUserHasCorp                      = errx.Newf(450090, "ErrUserHasCorp")
	ErrCorpIsNotInAudit                 = errx.Newf(450091, "ErrCorpIsNotInAudit")
	ErrInvalidCateID                    = errx.Newf(450091, "ErrInvalidCateID")
	ErrInvalidParentCateID              = errx.Newf(450091, "ErrInvalidParentCateID")
	ErrCateNameDuplicated               = errx.Newf(450092, "ErrCateNameDuplicated")
	ErrStaffCorpNotMatch                = errx.Newf(450092, "ErrStaffCorpNotMatch")
	ErrUserHasJoinCorp                  = errx.Newf(450093, "ErrUserHasJoinCorp")
	ErrOperateDoing                     = errx.Newf(450094, "ErrOperateDoing")
	ErrStaffInValid                     = errx.Newf(450095, "ErrStaffInValid")
	ErrRepeatRobotName                  = errx.Newf(450096, "ErrRepeatRobotName")
	ErrGetReferFail                     = errx.Newf(450098, "ErrGetReferFail")
	ErrMarkReferFail                    = errx.Newf(450099, "ErrMarkReferFail")
	ErrAuditNotFound                    = errx.Newf(450100, "ErrAuditNotFound")
	ErrReleaseIsNotInit                 = errx.Newf(450101, "ErrReleaseIsNotInit")
	ErrUnknownIndexID                   = errx.Newf(450102, "ErrUnknownIndexID")
	ErrTelephone                        = errx.Newf(450103, "ErrTelephone")
	ErrRunningTestRecords               = errx.Newf(450104, "ErrRunningTestRecords")
	ErrDeleteRunningTest                = errx.Newf(450105, "ErrDeleteRunningTest")
	ErrInvalidSampleSetExcel            = errx.Newf(450106, "ErrInvalidSampleSetExcel")
	ErrTestNum                          = errx.Newf(450107, "ErrTestNum")
	ErrTestRunning                      = errx.Newf(450108, "ErrTestRunning")
	ErrSameCreateTest                   = errx.Newf(450109, "ErrSameCreateTest")
	ErrTestNotExist                     = errx.Newf(450110, "ErrTestNotExist")
	ErrNoWaitJudgeRecords               = errx.Newf(450111, "ErrNoWaitJudgeRecords")
	ErrRecords                          = errx.Newf(450112, "ErrRecords")
	ErrExportTaskTypeNotFound           = errx.Newf(450115, "ErrExportTaskTypeNotFound")
	ErrRejectedQuestionNotFound         = errx.Newf(450117, "ErrRejectedQuestionNotFound")
	ErrRejectedQuestionNotModifyFound   = errx.Newf(450118, "ErrRejectedQuestionNotModifyFound")
	ErrCreateTest                       = errx.Newf(450119, "ErrCreateTest")
	ErrRejectedQuestionIsPendingRelease = errx.Newf(450119, "ErrRejectedQuestionIsPendingRelease")
	ErrOverCharacterSizeLimit           = errx.Newf(450120, "ErrOverCharacterSizeLimit")
	ErrOverCharacterSizeLimit4QiDian    = errx.Newf(450120, "ErrOverCharacterSizeLimit4QiDian")
	ErrUnsatisfiedReplyNotFound         = errx.Newf(450121, "ErrUnsatisfiedReplyNotFound")
	ErrExportUnsatisfiedReply           = errx.Newf(450122, "ErrExportUnsatisfiedReply")
	ErrExportrUnsatisfiedReplyTooMany   = errx.Newf(450123, "ErrExportrUnsatisfiedReplyTooMany")
	ErrUnsatisfiedReplyParams           = errx.Newf(450124, "ErrUnsatisfiedReplyParams")
	ErrUnsatisfiedReplyAdding           = errx.Newf(450125, "ErrUnsatisfiedReplyAdding")
	ErrAvatarURLFail                    = errx.Newf(450126, "ErrAvatarURLFail")
	ErrTransferUnsatisfiedCountParams   = errx.Newf(450127, "ErrTransferUnsatisfiedCountParams")
	ErrHTTPMethod                       = errx.Newf(450128, "ErrHTTPMethod")
	ErrEmptyBody                        = errx.Newf(450129, "ErrEmptyBody")
	ErrAuditCallbackDoing               = errx.Newf(450130, "ErrAuditCallbackDoing")
	ErrDocIsNotExcel                    = errx.Newf(450131, "ErrDocIsNotExcel")
	ErrDocIsExcel                       = errx.Newf(450132, "ErrDocIsExcel")
	ErrLoginTypeInvalid                 = errx.Newf(450133, "ErrLoginTypeInvalid")
	ErrLoginAccountPassword             = errx.Newf(450134, "ErrLoginAccountPassword")
	ErrLoginAccountFormat               = errx.Newf(450135, "ErrLoginAccountFormat")
	ErrLoginAccountExist                = errx.Newf(450136, "ErrLoginAccountExist")
	ErrUnknownDocType                   = errx.Newf(450137, "ErrUnknownDocType")
	ErrAttributeLabelSystem             = errx.Newf(450138, "ErrAttributeLabelSystem")
	ErrAttributeLabelAttrKeyInvalid     = errx.Newf(450139, "ErrAttributeLabelAttrKeyInvalid")
	ErrAttributeLabelAttrKeyExist       = errx.Newf(450140, "ErrAttributeLabelAttrKeyExist")
	ErrAttributeLabelAttrHasUsed        = errx.Newf(450141, "ErrAttributeLabelAttrHasUsed")
	ErrAttributeLabelAttrNameExist      = errx.Newf(450142, "ErrAttributeLabelAttrNameExist")
	ErrAttributeLabelAttrNameMaxLen     = errx.Newf(450143, "ErrAttributeLabelAttrNameMaxLen")
	ErrAttributeLabelNameRepeated       = errx.Newf(450144, "ErrAttributeLabelNameRepeated")
	ErrAttributeLabelHasRefer           = errx.Newf(450145, "ErrAttributeLabelHasRefer")
	ErrAttributeLabelNameMaxLen         = errx.Newf(450146, "ErrAttributeLabelNameMaxLen")
	ErrAttributeLabelLimit              = errx.Newf(450147, "ErrAttributeLabelLimit")
	ErrAttributeLabelSimilarMaxLen      = errx.Newf(450148, "ErrAttributeLabelSimilarMaxLen")
	ErrAttributeLabelSimilarLimit       = errx.Newf(450149, "ErrAttributeLabelSimilarLimit")
	ErrAttributeReferLimit              = errx.Newf(450150, "ErrAttributeReferLimit")
	ErrAttributeLabelNotFound           = errx.Newf(450151, "ErrAttributeLabelNotFound")
	ErrAttributeLabelAttrLimit          = errx.Newf(450152, "ErrAttributeLabelAttrLimit")
	ErrAttributeLabelUploading          = errx.Newf(450153, "ErrAttributeLabelUploading")
	ErrAttributeLabelSource             = errx.Newf(450154, "ErrAttributeLabelSource")
	ErrAttributeLabelRefer              = errx.Newf(450155, "ErrAttributeLabelRefer")
	ErrDocNotAllowEdit                  = errx.Newf(450156, "ErrDocNotAllowEdit")
	ErrAttributeLabelDocQaSync          = errx.Newf(450157, "ErrAttributeLabelDocQaSync")
	ErrAttributeLabelUpdating           = errx.Newf(450158, "ErrAttributeLabelUpdating")
	ErrAttributeLabelRepeated           = errx.Newf(450159, "ErrAttributeLabelRepeated")
	ErrQANotAllowEdit                   = errx.Newf(450160, "ErrQANotAllowEdit")
	ErrCreateAppealIng                  = errx.Newf(450161, "ErrCreateAppealIng")
	ErrQaForbidDelete                   = errx.Newf(450162, "ErrQaForbidDelete")
	ErrAppealNotFound                   = errx.Newf(450163, "ErrAppealNotFound")
	ErrAuditAppealIng                   = errx.Newf(450164, "ErrAuditAppealIng")
	ErrRetryRelease                     = errx.Newf(450165, "ErrRetryRelease")
	ErrRetryReleaseFail                 = errx.Newf(450166, "ErrRetryReleaseFail")
	ErrGetRelease                       = errx.Newf(450167, "ErrGetRelease")
	ErrReleasePause                     = errx.Newf(450168, "ErrReleasePause")
	ErrUinNotMatch                      = errx.Newf(450169, "ErrUinNotMatch")
	ErrSystemIntegratorNotFound         = errx.Newf(450170, "ErrSystemIntegratorNotFound")
	ErrResourcePermissionDenied         = errx.Newf(450171, "ErrResourcePermissionDenied")
	ErrSystemIntegratorUserParams       = errx.Newf(450172, "ErrSystemIntegratorUserParams")
	ErrFilterNotFound                   = errx.Newf(450173, "ErrFilterNotFound")
	// ErrGlobalKnowledgeNotFound            = errx.Newf(450174, "ErrGlobalKnowledgeNotFound")
	// ErrAddGlobalKnowledge                 = errx.Newf(450175, "ErrAddGlobalKnowledge")
	// ErrDelGlobalKnowledge                 = errx.Newf(450176, "ErrDelGlobalKnowledge")
	// ErrUpdGlobalKnowledge                 = errx.Newf(450177, "ErrUpdGlobalKnowledge")
	// ErrGetGlobalKnowledge                 = errx.Newf(450178, "ErrGetGlobalKnowledge")
	// ErrForceSyncGlobalKnowledge           = errx.Newf(450179, "ErrForceSyncGlobalKnowledge")
	ErrActivateProduct                    = errx.Newf(450180, "ErrActivateProduct")
	ErrParseFileTimeout                   = errx.Newf(450181, "ErrParseFileTimeout")
	ErrEmptyName                          = errx.Newf(450182, "ErrEmptyName")
	ErrEmptyAvatar                        = errx.Newf(450183, "ErrEmptyAvatar")
	ErrDocParseTaskNotFound               = errx.Newf(450184, "ErrDocParseTaskNotFound")
	ErrDocParseResultCallBackFail         = errx.Newf(450185, "ErrDocParseResultCallBackFail")
	ErrDocParseResultCallBackErr          = errx.Newf(450186, "ErrDocParseResultCallBackErr")
	ErrDocParseCharSizeExceeded           = errx.Newf(450187, "ErrDocParseCharSizeExceeded")
	ErrDocParseCharSizeExceeded4QiDian    = errx.Newf(450187, "ErrDocParseCharSizeExceeded4QiDian")
	ErrDocParseCosURLNotFound             = errx.Newf(450188, "ErrDocParseCosURLNotFound")
	ErrRobotOrDocNotFound                 = errx.Newf(450189, "ErrRobotOrDocNotFound")
	ErrUpdateDocStatusFail                = errx.Newf(450190, "ErrUpdateDocStatusFail")
	ErrUpdateDocParseTaskStatusFail       = errx.Newf(450191, "ErrUpdateDocParseTaskStatusFail")
	ErrCreateDocToQATaskFail              = errx.Newf(450192, "ErrCreateDocToQATaskFail")
	ErrCreateDocToIndexTaskFail           = errx.Newf(450193, "ErrCreateDocToIndexTaskFail")
	ErrUpdateDocStatusAndCharSizeFail     = errx.Newf(450194, "ErrUpdateDocStatusAndCharSizeFail")
	ErrDocParseTaskFailNotFound           = errx.Newf(450195, "ErrDocParseTaskFailNotFound")
	ErrIllegalReleaseStatus               = errx.Newf(450196, "ErrIllegalReleaseStatus")
	ErrUpdateRobotUsedCharSizeFail        = errx.Newf(450197, "ErrUpdateRobotUsedCharSizeFail")
	ErrExcelParseFailInDateValidity       = errx.Newf(450198, "ErrExcelParseFailInDateValidity")
	ErrExcelParseFailNotHalfHour          = errx.Newf(450199, "ErrExcelParseFailNotHalfHour")
	ErrDocToQaExpiredFail                 = errx.Newf(450200, "ErrDocToQaExpiredFail")
	ErrFileExtNotMatch                    = errx.Newf(450201, "ErrFileExtNotMatch")
	ErrRetryDocParseTaskFail              = errx.Newf(450202, "ErrRetryDocParseTaskFail")
	ErrRobotSplitStrategyFail             = errx.Newf(450203, "ErrRobotSplitStrategyFail")
	ErrStopDocParseFail                   = errx.Newf(450204, "ErrStopDocParseFail")
	ErrCreateAuditFail                    = errx.Newf(450205, "ErrCreateAuditFail")
	ErrIntentNotFound                     = errx.Newf(450206, "ErrIntentNotFound")
	ErrCreateDocParseSplitSegmentTaskFail = errx.Newf(450208, "ErrCreateDocParseSplitSegmentTaskFail")
	ErrCreateDocParseSplitQATaskFail      = errx.Newf(450209, "ErrCreateDocParseSplitQATaskFail")
	ErrAttributeLabelDocQa                = errx.Newf(450210, "ErrAttributeLabelDocQa")
	ErrTrailProductFail                   = errx.Newf(450210, "ErrTrailProductFail")
	ErrMasterAccount                      = errx.Newf(450211, "ErrMasterAccount")
	ErrProductPermissionNotExist          = errx.Newf(450212, "ErrProductPermissionNotExist")
	ErrProductAlreadyOpen                 = errx.Newf(450213, "ErrProductAlreadyOpen")
	ErrDocCannotBeSubmittedForAudit       = errx.Newf(450215, "ErrDocCannotBeSubmittedForAudit")
	ErrDocNoNeedAudit                     = errx.Newf(450216, "ErrDocNoNeedAudit")
	ErrEmbeddingVersionNotMatch           = errx.Newf(450220, "ErrEmbeddingVersionNotMatch")
	ErrEmbeddingUpgrading                 = errx.Newf(450221, "ErrEmbeddingUpgrading")
	ErrAttributeLabelNotSupported         = errx.Newf(450222, "ErrAttributeLabelNotSupported")
	ErrAttributeBelongsToDifferentApps    = errx.Newf(450223, "ErrAttributeBelongsToDifferentApps")
	ErrUnknownDocTypeForIndexType         = errx.Newf(450224, "ErrUnknownDocTypeForIndexType")
	ErrAppUpgrading                       = errx.Newf(450225, "ErrAppUpgrading")
	ErrFileSizeTooBig                     = errx.Newf(450226, "ErrFileSizeTooBig")
	ErrAttributeLabelEmpty                = errx.Newf(450227, "ErrAttributeLabelEmpty")
	ErrOverModelTokenLimit                = errx.Newf(450228, "ErrOverModelTokenLimit")
	ErrBotOverCharacterSizeLimit          = errx.Newf(450229, "ErrBotOverCharacterSizeLimit")
	ErrReqQaListExceedLimit               = errx.Newf(450230, "ErrReqQaListExceedLimit")
	ErrAppBizIDParams                     = errx.Newf(450231, "ErrAppBizIDParams")
	ErrGetAppFail                         = errx.Newf(450300, "ErrGetAppFail")
	ErrAppTypeNotFound                    = errx.Newf(450301, "ErrAppTypeNotFound")
	ErrAppQuotaNotEnough                  = errx.Newf(450400, "ErrAppQuotaNotEnough")
	ErrAppTypeInvalid                     = errx.Newf(450401, "ErrAppTypeInvalid")
	ErrNotFoundModel                      = errx.Newf(450402, "ErrNotFoundModel")
	ErrAppNotFound                        = errx.Newf(450403, "ErrAppNotFound")
	ErrAppTypeSupportFilters              = errx.Newf(450404, "ErrAppTypeSupportFilters")
	ErrAppScenceNotSupport                = errx.Newf(450405, "ErrAppScenceNotSupport")
	ErrAppNotSupportModelList             = errx.Newf(450406, "ErrAppNotSupportModelList")
	ErrAppInitFail                        = errx.Newf(450407, "ErrAppInitFail")
	ErrReleaseConfigNotFound              = errx.Newf(450412, "ErrReleaseConfigNotFound")
	ErrCorpTrialExpired                   = errx.Newf(450415, "ErrCorpTrialExpired")
	ErrNotInWhiteList                     = errx.Newf(450416, "ErrNotInWhiteList")
	ErrNotDefaultModel                    = errx.Newf(450417, "ErrNotDefaultModel")
	ErrNotInvalidModel                    = errx.Newf(450418, "ErrNotInvalidModel")
	ErrNotAppConfig                       = errx.Newf(450419, "ErrNotAppConfig")
	ErrAppNotPublish                      = errx.Newf(450420, "ErrAppNotPublish")
	ErrCorpHasRegister                    = errx.Newf(450421, "ErrCorpHasRegister")
	ErrModuleNotExist                     = errx.Newf(450422, "ErrModuleNotExist")
	ErrCreateIntentFail                   = errx.Newf(450426, "ErrCreateIntentFail")
	ErrUpdateIntentFail                   = errx.Newf(450427, "ErrUpdateIntentFail")
	ErrGetIntentPolicyFail                = errx.Newf(450428, "ErrGetIntentPolicyFail")
	ErrUpdateIntentPolicyFail             = errx.Newf(450429, "ErrUpdateIntentPolicyFail")
	ErrCorpAppNotEqual                    = errx.Newf(450438, "ErrCorpAppNotEqual")
	ErrFileUrlFail                        = errx.Newf(450439, "ErrFileUrlFail")
	ErrFileUrlNotFound                    = errx.Newf(450440, "ErrFileUrlNotFound")
	ErrAppealTypeNotMatch                 = errx.Newf(450902, "ErrAppealTypeNotMatch")
	ErrDocQAFileFail                      = errx.Newf(450903, "ErrDocQAFileFail")
	ErrDocIDFail                          = errx.Newf(450904, "ErrDocIDFail")
	ErrDocFilterFlagFail                  = errx.Newf(450905, "ErrDocFilterFlagFail")
	ErrResumeQAMaxCountLimit              = errx.Newf(450906, "ErrResumeQAMaxCountLimit")
	ErrDocQaTaskNotFound                  = errx.Newf(460001, "ErrDocQaTaskNotFound")
	ErrDocQaTaskStatusFail                = errx.Newf(460002, "ErrDocQaTaskStatusFail")
	ErrGetSegmentFail                     = errx.Newf(460003, "ErrGetSegmentFail")
	ErrGetQaExistsFail                    = errx.Newf(460004, "ErrGetQaExistsFail")
	ErrGetListQaTaskFail                  = errx.Newf(460005, "ErrGetListQaTaskFail")
	ErrDeleteQaTaskStatusFail             = errx.Newf(460006, "ErrDeleteQaTaskStatusFail")
	ErrCancelQaTaskStatusFail             = errx.Newf(460007, "ErrCancelQaTaskStatusFail")
	ErrStopQaTaskStatusFail               = errx.Newf(460008, "ErrStopQaTaskStatusFail")
	ErrContinueQaTaskStatusFail           = errx.Newf(460009, "ErrContinueQaTaskStatusFail")
	ErrQaTaskSegmentFail                  = errx.Newf(460010, "ErrQaTaskSegmentFail")
	ErrQaTaskExistsOrgDataFail            = errx.Newf(460011, "ErrQaTaskExistsOrgDataFail")
	ErrGeneratingFail                     = errx.Newf(460012, "ErrGeneratingFail")
	ErrGeneratingNoTokenBalance           = errx.Newf(460013, "ErrGeneratingNoTokenBalance")
	ErrModifyQaExpireFail                 = errx.Newf(460014, "ErrModifyQaExpireFail")
	ErrModifyQaDocFail                    = errx.Newf(460015, "ErrModifyQaDocFail")
	ErrRetryQaTaskStatusFail              = errx.Newf(460016, "ErrRetryQaTaskStatusFail")
	ErrSynonymsNotFound                   = errx.Newf(460018, "ErrSynonymsNotFound")
	ErrSynonymsForbidDelete               = errx.Newf(460019, "ErrSynonymsForbidDelete")
	ErrExportSynonyms                     = errx.Newf(460020, "ErrExportSynonyms")
	ErrExportSynonymsTooMany              = errx.Newf(460021, "ErrExportSynonymsTooMany")
	ErrSynonymsInvalidStandard            = errx.Newf(460022, "ErrSynonymsInvalidStandard")
	ErrSynonymsInvalidWord                = errx.Newf(460023, "ErrSynonymsInvalidWord")
	ErrSynonymsTooMany                    = errx.Newf(460024, "ErrSynonymsTooMany")
	ErrSynonymsIsDeleted                  = errx.Newf(460025, "ErrSynonymsIsDeleted")
	ErrSynonymsListUploading              = errx.Newf(460026, "ErrSynonymsListUploading")
	ErrSynonymsInvalidDupError            = errx.Newf(460027, "ErrSynonymsInvalidDupError")
	ErrSynonymsTaskNotFound               = errx.Newf(460028, "ErrSynonymsTaskNotFound")
	ErrSynonymsTaskImportFailWithConflict = errx.Newf(460029, "ErrSynonymsTaskImportFailWithConflict")
	ErrAppealCallbackDoing                = errx.Newf(460030, "ErrAppealCallbackDoing")
	ErrDescribeDocLimit                   = errx.Newf(460031, "ErrDescribeDocLimit")
	ErrCreateQADocType                    = errx.Newf(460032, "ErrCreateQADocType")
	ErrStopTestStatus                     = errx.Newf(460033, "ErrStopTestStatus")
	ErrRetryTestStatus                    = errx.Newf(460034, "ErrRetryTestStatus")
	ErrDocCannotRename                    = errx.Newf(460035, "ErrDocCannotRename")
	ErrGenerateSimilarParams              = errx.Newf(460035, "ErrGenerateSimilarParams")
	ErrDocSegmentPrefixNotMatch           = errx.Newf(460036, "ErrDocSegmentPrefixNotMatch")
	ErrDocNameNotMatch                    = errx.Newf(460037, "ErrDocNameNotMatch")
	ErrDocNameExtNotMatch                 = errx.Newf(460038, "ErrDocNameExtNotMatch")
	ErrDocNameVerifyFailed                = errx.Newf(460039, "ErrDocNameVerifyFailed")
	ErrDocNameNotChanged                  = errx.Newf(460040, "ErrDocNameNotChanged")
	ErrDocDiffDocNotFound                 = errx.Newf(460041, "ErrDocDiffDocNotFound")
	ErrCreateDocDiffTaskFail              = errx.Newf(460042, "ErrCreateDocDiffTaskFail")
	ErrCreateDocDiffTaskInTaskFail        = errx.Newf(460043, "ErrCreateDocDiffTaskInTaskFail")
	ErrCreateDocDiffTaskInQaFail          = errx.Newf(460044, "ErrCreateDocDiffTaskInQaFail")
	ErrCreateDocDiffTaskDescribeFail      = errx.Newf(460045, "ErrCreateDocDiffTaskDescribeFail")
	ErrHandleDocDiffSizeFail              = errx.Newf(460046, "ErrHandleDocDiffSizeFail")
	ErrHandleDocDiffFail                  = errx.Newf(460047, "ErrHandleDocDiffFail")
	ErrHandleDocDiffNotFound              = errx.Newf(460048, "ErrHandleDocDiffNotFound")
	ErrHandleDocDiffNotFail               = errx.Newf(460049, "ErrHandleDocDiffNotFail")
	ErrDocDiffQaNotRetry                  = errx.Newf(460050, "ErrDocDiffQaNotRetry")
	ErrCreateDocDiffTaskDocTypeFail       = errx.Newf(460051, "ErrCreateDocDiffTaskDocTypeFail")
	ErrDocDiffTaskRunIng                  = errx.Newf(460052, "ErrDocDiffTaskRunIng")
	ErrHandleDiffTypeOperationFail        = errx.Newf(460053, "ErrHandleDiffTypeOperationFail")
	ErrHandleDocOperationFail             = errx.Newf(460054, "ErrHandleDocOperationFail")
	ErrHandleQaOperationFail              = errx.Newf(460055, "ErrHandleQaOperationFail")
	ErrHandleQaOperationReNameFail        = errx.Newf(460056, "ErrHandleQaOperationReNameFail")
	ErrDocIsModifyingOrDeleting           = errx.Newf(460057, "ErrDocIsModifyingOrDeleting")
	ErrQaIsModifyingOrDeleting            = errx.Newf(460058, "ErrQaIsModifyingOrDeleting")
	ErrVideoURLFail                       = errx.Newf(470100, "ErrVideoURLFail")
	ErrInvalidDocQaExcel                  = errx.Newf(470101, "ErrInvalidDocQaExcel")
	ErrGenerateQALimitFail                = errx.Newf(470102, "ErrGenerateQALimitFail")
	ErrHandleDocDiffTaskInDiffFail        = errx.Newf(470103, "ErrHandleDocDiffTaskInDiffFail")
	ErrHandleDocDiffTaskDocTypeFail       = errx.Newf(470104, "ErrHandleDocDiffTaskDocTypeFail")
	ErrHandleDocDiffTaskTypeFail          = errx.Newf(470105, "ErrHandleDocDiffTaskTypeFail")
	ErrHandleDocDiffTaskDocNotFoundFail   = errx.Newf(470106, "ErrHandleDocDiffTaskDocNotFoundFail")
	ErrInvalidExpireTime                  = errx.Newf(470107, "ErrInvalidExpireTime")
	ErrUserIdInCustomVariablesIsEmpty     = errx.Newf(470108, "ErrUserIdInCustomVariablesIsEmpty")
	ErrReleaseMaxCount                    = errx.Newf(470109, "ErrReleaseMaxCount")
	ErrGetReleaseFail                     = errx.Newf(470110, "ErrGetReleaseFail")
	ErrContextInvalid                     = errx.Newf(471003, "ErrContextInvalid")
	ErrParameterInvalid                   = errx.Newf(471004, "ErrParameterInvalid")
	ErrRelatedAppExist                    = errx.Newf(471005, "ErrRelatedAppExist")
	ErrCreateSharedKnowledgeAppFailed     = errx.Newf(471006, "ErrCreateSharedKnowledgeAppFailed")
	ErrDeleteSharedKnowledgeAppFailed     = errx.Newf(471007, "ErrDeleteSharedKnowledgeAppFailed")
	ErrGetUserNameFailed                  = errx.Newf(471008, "ErrGetUserNameFailed")
	ErrCreateSharedKnowledgeRecordFailed  = errx.Newf(471009, "ErrCreateSharedKnowledgeRecordFailed")
	ErrQuerySharedKnowledgeRecordFailed   = errx.Newf(471010, "ErrQuerySharedKnowledgeRecordFailed")
	ErrSharedKnowledgeConvertFailed       = errx.Newf(471011, "ErrSharedKnowledgeConvertFailed")
	ErrGetShareKnowledgeAppListFailed     = errx.Newf(471012, "ErrGetShareKnowledgeAppListFailed")
	ErrDeleteSharedKnowledgeRecordFailed  = errx.Newf(471013, "ErrDeleteSharedKnowledgeRecordFailed")
	ErrSharedKnowledgeRecordNotFound      = errx.Newf(471014, "ErrSharedKnowledgeRecordNotFound")
	ErrKnowledgeSchemaTaskNotFound        = errx.Newf(471015, "ErrKnowledgeSchemaTaskNotFound")
	ErrSharedKnowledgeExist               = errx.Newf(471016, "ErrSharedKnowledgeExist")
	ErrSharedKnowledgeNameQueryFailed     = errx.Newf(471017, "ErrSharedKnowledgeNameQueryFailed")
	ErrReleaseQaMaxCount                  = errx.Newf(471018, "ErrReleaseQaMaxCount")
	ErrBatchDownloadMaxCount              = errx.Newf(471019, "ErrBatchDownloadMaxCount")
	ErrQueryKnowledgeModelConfigFailed    = errx.Newf(471020, "ErrQueryKnowledgeModelConfigFailed")
	ErrDeleteKnowledgeModelConfigFailed   = errx.Newf(471021, "ErrDeleteKnowledgeModelConfigFailed")
	ErrAttributeLabelReferLimit           = errx.Newf(471022, "ErrAttributeLabelReferLimit")
	ErrDocStatusNotStable                 = errx.Newf(471023, "ErrDocStatusNotStable")

	ErrDescribeServiceRoleFailed     = errx.Newf(471024, "ErrDescribeServiceRoleFailed")
	ErrServiceRoleUnavailable        = errx.Newf(471025, "ErrServiceRoleUnavailable")
	ErrAssumeServiceRoleFailed       = errx.Newf(471026, "ErrAssumeServiceRoleFailed")
	ErrUserCOSNotReadyFailed         = errx.Newf(471027, "ErrUserCOSNotReadyFailed")
	ErrListBucketWithCORSFailed      = errx.Newf(471028, "ErrListBucketWithCORSFailed")
	ErrRefreshCorpCOSDocStatusFail   = errx.Newf(471029, "ErrRefreshCorpCOSDocStatusFail")
	ErrRefreshCorpCOSDocUserAuthFail = errx.Newf(471030, "ErrRefreshCorpCOSDocUserAuthFail")
	ErrRefreshCorpCOSDocFail         = errx.Newf(471031, "ErrRefreshCorpCOSDocFail")

	// 连接外部数据库的错误码
	ErrOpenDbSourceFail              = errx.Newf(4720000, "ErrOpenDbSourceFail")
	ErrDbSourceTypeNotSupport        = errx.Newf(4720001, "ErrDbSourceTypeNotSupport")
	ErrDbSourceTableBlankFail        = errx.Newf(4720002, "ErrDbSourceTableBlankFail")
	ErrTypeConvertFail               = errx.Newf(4720003, "ErrTypeConvertFail")
	ErrAddDbSourceFail               = errx.Newf(4720004, "ErrAddDbSourceFail")
	ErrUpdateDbSourceGetFail         = errx.Newf(4720005, "ErrUpdateDbSourceGetFail")
	ErrUpdateDbSourceCreateFail      = errx.Newf(4720006, "ErrUpdateDbSourceCreateFail")
	ErrPageNumberInvalid             = errx.Newf(4720007, "ErrPageNumberInvalid")
	ErrDataNotExistOrIsDeleted       = errx.Newf(4720008, "ErrDataNotExistOrIsDeleted")
	ErrDbTableNumIsInvalid           = errx.Newf(4720009, "ErrDbTableNumIsInvalid")
	ErrNameInvalid                   = errx.Newf(4720010, "ErrNameInvalid")
	ErrDbNameBanned                  = errx.Newf(4720011, "ErrDbNameBanned")
	ErrDbNameIsInvalid               = errx.Newf(4720012, "ErrDbNameIsInvalid")
	ErrPasswordDecodeFail            = errx.Newf(4720013, "ErrPasswordDecodeFail")
	ErrDbSourceTimeOut               = errx.Newf(4720014, "ErrDbSourceTimeOut")
	ErrDbSourceNoPermission          = errx.Newf(4720015, "ErrDbSourceNoPermission")
	ErrDbSourceTableEmpty            = errx.Newf(4720016, "ErrDbSourceTableEmpty")
	ErrDataBase                      = errx.Newf(4720017, "ErrDataBase")
	ErrInvalidFields                 = errx.Newf(4720018, "ErrInvalidFields")
	ErrWriteIntoEsFail               = errx.Newf(4720019, "ErrWriteIntoEsFail")
	ErrDbTableSizeInvalid            = errx.Newf(4720020, "ErrDbTableSizeInvalid")
	ErrDbSourceInputExtraLong        = errx.Newf(4720021, "ErrDbSourceInputExtraLong")
	ErrDbSourceParsingFailed         = errx.Newf(4720022, "ErrDbSourceParsingFailed")
	ErrDbSourceTableColumnNotExist   = errx.Newf(4720023, "ErrDbSourceTableColumnNotExist")
	ErrDbSourceNotEnabled            = errx.Newf(4720024, "ErrDbSourceNotEnabled")
	ErrDbTableStatus                 = errx.Newf(4720025, "ErrDbTableStatus")
	ErrDbTableIsNotExist             = errx.Newf(4720026, "ErrDbTableIsNotExist")
	ErrDbSourceLimitExceeded         = errx.Newf(4720027, "ErrDbSourceLimitExceeded")
	ErrDbTableStatusForText2Sql      = errx.Newf(4720028, "ErrDbTableStatusForText2Sql")
	ErrText2sqlTableNums             = errx.Newf(4720029, "ErrText2sqlTableNums")
	ErrDbSourceStatusForChangeEnable = errx.Newf(4720030, "ErrDbSourceStatusForChangeEnable")
	ErrDbTableNotExistForProd        = errx.Newf(4720031, "ErrDbTableNotExistForProd")
	ErrDbSourceStatusForText2Sql     = errx.Newf(4720032, "ErrDbSourceStatusForText2Sql")
	ErrText2sqlTimeOut               = errx.Newf(4720033, "ErrText2sqlTimeOut")
	ErrInvalidDbSourceHost           = errx.Newf(4720034, "ErrInvalidDbSourceHost")
	ErrDBSchemaQueryFailed           = errx.Newf(4720035, "ErrDBSchemaQueryFailed")
	ErrDbSchemaNotSupport            = errx.Newf(4720036, "ErrDbSchemaNotSupport")

	// 权限相关报错
	ErrCommonFail                          = errx.Newf(470107, "ErrCommonFail")
	ErrCustUserNameFail                    = errx.Newf(470108, "ErrCustUserNameFail")
	ErrThirdUserIdFail                     = errx.Newf(470109, "ErrThirdUserIdFail")
	ErrCustUserNameExist                   = errx.Newf(470110, "ErrCustUserNameExist")
	ErrLkeUserIdExist                      = errx.Newf(470111, "ErrLkeUserIdExist")
	ErrUserRoleEmpty                       = errx.Newf(470112, "ErrUserRoleEmpty")
	ErrCreateUserFail                      = errx.Newf(470113, "ErrCreateUserFail")
	ErrUserNotExist                        = errx.Newf(470113, "ErrUserNotExist")
	ErrBatchEditUserId                     = errx.Newf(470114, "ErrBatchEditUserId")
	ErrUpdateUserFail                      = errx.Newf(470115, "ErrUpdateUserFail")
	ErrGetUserListFail                     = errx.Newf(470116, "ErrGetUserListFail")
	ErrGetUserRoleListFail                 = errx.Newf(470117, "ErrGetUserRoleListFail")
	ErrGetRoleListFail                     = errx.Newf(470118, "ErrGetRoleListFail")
	ErrDetailUserFail                      = errx.Newf(470118, "ErrDetailUserFail")
	ErrDeleteUserFail                      = errx.Newf(470118, "ErrDeleteUserFail")
	ErrDeleteUserRoleFail                  = errx.Newf(470119, "ErrDeleteUserRoleFail")
	ErrGetUserConfigFail                   = errx.Newf(470120, "ErrGetUserConfigFail")
	ErrSetCustUserConfigFail               = errx.Newf(470121, "ErrSetCustUserConfigFail")
	ErrSetThirdAclNotToken                 = errx.Newf(470122, "ErrSetThirdAclNotToken")
	ErrSetThirdAclNotSecret                = errx.Newf(470123, "ErrSetThirdAclNotSecret")
	ErrSetThirdAclTypeFail                 = errx.Newf(470124, "ErrSetThirdAclTypeFail")
	ErrSetThirdAclTokenUrlFail             = errx.Newf(470125, "ErrSetThirdAclTokenUrlFail")
	ErrSetThirdAclAclUrlFail               = errx.Newf(470126, "ErrSetThirdAclAclUrlFail")
	ErrSetThirdAclFail                     = errx.Newf(470127, "ErrSetThirdAclFail")
	ErrGetThirdAclFail                     = errx.Newf(470128, "ErrGetThirdAclFail")
	ErrRoleNameFail                        = errx.Newf(470129, "ErrRoleNameFail")
	ErrRoleNameExist                       = errx.Newf(470130, "ErrRoleNameExist")
	ErrRoleSearchTypeFail                  = errx.Newf(470131, "ErrRoleSearchTypeFail")
	ErrRoleKnowledgeFail                   = errx.Newf(470132, "ErrRoleKnowledgeFail")
	ErrRoleKnowledgeTypeFail               = errx.Newf(470133, "ErrRoleKnowledgeTypeFail")
	ErrDeleteRoleFail                      = errx.Newf(470134, "ErrDeleteRoleFail")
	ErrRoleNotExist                        = errx.Newf(470135, "ErrRoleNotExist")
	ErrRoleModifyFail                      = errx.Newf(470136, "ErrRoleModifyFail")
	ErrSetCustUserConfigRoleFail           = errx.Newf(470137, "ErrSetCustUserConfigRoleFail")
	ErrSetThirdAclConfigLock               = errx.Newf(470138, "ErrSetThirdAclConfigLock")
	ErrSetAppShareKGFailed                 = errx.Newf(470139, "ErrSetAppShareKGFailed")
	ErrGetAppShareKGListFailed             = errx.Newf(470140, "ErrGetAppShareKGListFailed")
	ErrRetrieveBaseSharedKGFailed          = errx.Newf(470141, "ErrRetrieveBaseSharedKGFailed")
	ErrGetAppFailed                        = errx.Newf(470142, "ErrGetAppFailed")
	ErrGetKnowledgeFailed                  = errx.Newf(470143, "ErrGetKnowledgeFailed")
	ErrDocIsDisabled                       = errx.Newf(470144, "ErrDocIsDisabled")
	ErrDocIsEnabled                        = errx.Newf(470145, "ErrDocIsEnabled")
	ErrRoleConditionFail                   = errx.Newf(470146, "ErrRoleConditionFail")
	ErrRoleTypeFail                        = errx.Newf(470147, "ErrRoleTypeFail")
	ErrQAIsDisabled                        = errx.Newf(470148, "ErrQAIsDisabled")
	ErrQAIsEnabled                         = errx.Newf(470149, "ErrQAIsEnabled")
	ErrUserMaxLimit                        = errx.Newf(470150, "ErrUserMaxLimit")
	ErrRoleMaxLimit                        = errx.Newf(470151, "ErrRoleMaxLimit")
	ErrGetDocSegmentTooLarge               = errx.Newf(470152, "ErrGetDocSegmentTooLarge")
	ErrDocSegmentNotFound                  = errx.Newf(470153, "ErrDocSegmentNotFound")
	ErrDocSegmentKeywordsMaxLimit          = errx.Newf(470154, "ErrDocSegmentKeywordsMaxLimit")
	ErrGetEmbedding                        = errx.Newf(470155, "ErrGetEmbedding")
	ErrGetEmbeddingEmpty                   = errx.Newf(470156, "ErrGetEmbeddingEmpty")
	ErrDocNotSupportInterveneFailed        = errx.Newf(470157, "ErrDocNotSupportInterveneFailed")
	ErrDocSegmentOperationNotAllowedFailed = errx.Newf(470158, "ErrDocSegmentOperationNotAllowedFailed")
	ErrDocSegmentSheetNotFound             = errx.Newf(470159, "ErrDocSegmentSheetNotFound")
	ErrCateTypeFail                        = errx.Newf(470160, "ErrCateTypeFail")
	ErrDocSegmentFilterInvalid             = errx.Newf(470161, "ErrDocSegmentFilterInvalid")
	ErrRefreshTxDocStatusFail              = errx.Newf(470162, "ErrRefreshTxDocStatusFail")
	ErrRefreshTxDocUserAuthFail            = errx.Newf(470163, "ErrRefreshTxDocUserAuthFail")
	ErrRefreshTxDocFail                    = errx.Newf(470164, "ErrRefreshTxDocFail")
	ErrInterveneDataFail                   = errx.Newf(470165, "ErrInterveneDataFail")
	ErrEmbeddingModelUpdating              = errx.Newf(470166, "ErrEmbeddingModelUpdating")
	ErrEmbeddingModelUpdateFailed          = errx.Newf(470167, "ErrEmbeddingModelUpdateFailed")
	ErrTxDownloadDocFailed                 = errx.Newf(470168, "ErrTxDownloadDocFailed")
	ErrDescribeExceededKnowledgeListFailed = errx.Newf(470169, "ErrDescribeExceededKnowledgeListFailed")
	ErrResumeExceedKnowledgeFailed         = errx.Newf(470170, "ErrResumeExceedKnowledgeFailed")
	ErrCheckAttributeTypeUnknown           = errs.Newf(470171, "ErrCheckAttributeTypeUnknown")
	ErrThirdDocWithoutAuth                 = errs.Newf(470172, "ErrThirdDocWithoutAuth")
	ErrRefreshDocFail                      = errx.Newf(470173, "ErrRefreshDocFail")
	ErrConvertBizIdParamsEmpty             = errx.Newf(470174, "ErrConvertBizIdParamsEmpty")
	ErrConvertBizIdUnknownIdType           = errx.Newf(470175, "ErrConvertBizIdUnknownIdType")
	ErrGetAppShareProdKGListFailed         = errx.Newf(470176, "ErrGetAppShareProdKGListFailed")
	ErrExportKbPackageOverMaxLimit         = errx.Newf(470178, "ErrExportKbPackageOverMaxLimit")

	ErrInvalidRetrievalEnableScope = errs.Newf(470172, "ErrInvalidRetrievalEnableScope")

	// 下面的7位错误码不要再增加了，接着上面的6位错误码继续加
	ErrQAIsNotExist                = errx.Newf(4500141, "ErrQAIsNotExist")
	ErrRealtimeDocParseFailed      = errx.Newf(4505001, "ErrRealtimeDocParseFailed")
	ErrParamsNotExpected           = errx.Newf(4505002, "ErrParamsNotExpected")
	ErrDocCharSizeNotAllowCreateQA = errx.Newf(4506001, "ErrDocCharSizeNotAllowCreateQA")
	ErrRetrievalConfig             = errx.Newf(4507001, "ErrRetrievalConfig")
	ErrNoTokenBalance              = errx.Newf(4507002, "ErrNoTokenBalance")
	ErrDocNotStable                = errx.Newf(4508000, "ErrDocNotStable")
	ErrQANotStable                 = errx.Newf(4508001, "ErrQANotStable")

	ErrQuotaModel = errx.Newf(4900001, "ErrQuotaModel") //该套餐配额不允许使用第三方模型
)

// ErrWrapf 错误封装
func ErrWrapf(err error, format string, args ...any) error {
	return errx.Wrapf(err, errx.Code(err), format, args...)
}

// ConvertErrMsg 转换错误信息，可根据集成商需求定制错误信息
func ConvertErrMsg(systemIntegratorName string, err error) error {
	if errMap, ok1 := ErrMap[systemIntegratorName]; ok1 {
		if newErr, ok2 := errMap[err]; ok2 {
			return newErr
		}
	}
	return err
}

// ConvertErr2i18nKeyMsg 转换错误信息为i18n key，主要用在推送通知场景转换报错信息
func ConvertErr2i18nKeyMsg(err error) string {
	if i18nKey, ok := Err2KeyMap[err]; ok {
		return i18nKey
	}
	return err.Error()
}

// Is 判断err是否相等
func Is(err, target error) bool {
	return errors.Is(err, target) || errs.Code(err) == errs.Code(target)
}
