package errs

import (
	"errors"

	"git.code.oa.com/trpc-go/trpc-go/errs"
	"git.woa.com/adp/common/x/trpcx/plugins/i18n"
)

const (
	SystemIntegratorNameQiDian = "企点" // 集成商表t_system_integrator中企点的名称
)

// ErrMap 集成商定制错误信息映射表 集成商id -> 通用错误信息 -> 定制错误信息
var ErrMap = map[string]map[error]error{
	SystemIntegratorNameQiDian: {
		ErrOverCharacterSizeLimit:   ErrOverCharacterSizeLimit4QiDian,
		ErrDocParseCharSizeExceeded: ErrDocParseCharSizeExceeded4QiDian,
	},
}

var (
	ErrCodeExcelContent               = i18n.Newf(450081, "ErrCodeExcelContent")
	ErrCodeAnswerTooLong              = i18n.Newf(400035, "ErrCodeAnswerTooLong")
	ErrCodeAnswerTooShort             = i18n.Newf(400031, "ErrCodeAnswerTooShort")
	ErrCodeQuestionTooLong            = i18n.Newf(400034, "ErrCodeQuestionTooLong")
	ErrCodeQuestionTooShort           = i18n.Newf(400030, "ErrCodeQuestionTooShort")
	ErrCodeCateNameTooLong            = i18n.Newf(400032, "ErrCodeCateNameTooLong")
	ErrCodeCateNameTooShort           = i18n.Newf(400029, "ErrCodeCateNameTooShort")
	ErrCodeImportLengthExceedLimit    = i18n.Newf(450083, "ErrCodeImportLengthExceedLimit")
	ErrCodeCateCountExceed            = i18n.Newf(450084, "ErrCodeCateCountExceed")
	ErrCodeUserHasJoinCorp            = i18n.Newf(450115, "ErrCodeUserHasJoinCorp")
	ErrCodeExcelNumTooFew             = i18n.Newf(400037, "ErrCodeExcelNumTooFew")
	ErrCodeExcelNumTooMany            = i18n.Newf(400038, "ErrCodeExcelNumTooMany")
	ErrCodeSimilarQuestionExceedLimit = i18n.Newf(400039, "ErrCodeSimilarQuestionExceedLimit")
	ErrCodeSimilarQuestionRepeated    = i18n.Newf(400040, "ErrCodeSimilarQuestionRepeated")
	ErrCodeAIConf                     = i18n.Newf(450085, "ErrCodeAIConf")

	ErrAlreadyLocked                      = i18n.Newf(400028, "ErrAlreadyLocked")
	ErrRobotInitFail                      = i18n.Newf(400033, "ErrRobotInitFail")
	ErrUnknownSplitModel                  = i18n.Newf(400036, "ErrUnknownSplitModel")
	ErrCorpNotFound                       = i18n.Newf(400037, "ErrCorpNotFound")
	ErrUnknownSplitProc                   = i18n.Newf(400037, "ErrUnknownSplitProc")
	ErrDocNotFound                        = i18n.Newf(450001, "ErrDocNotFound")
	ErrPermissionDenied                   = i18n.Newf(450002, "ErrPermissionDenied")
	ErrDocStatusNotAllowReCreateQA        = i18n.Newf(450003, "ErrDocStatusNotAllowReCreateQA")
	ErrUserNotFound                       = i18n.Newf(450004, "ErrUserNotFound")
	ErrStaffNotFound                      = i18n.Newf(450005, "ErrStaffNotFound")
	ErrUserIsInValid                      = i18n.Newf(450005, "ErrUserIsInValid")
	ErrSessionNotFound                    = i18n.Newf(450006, "ErrSessionNotFound")
	ErrSmsSendFailed                      = i18n.Newf(450007, "ErrSmsSendFailed")
	ErrVerifyCode                         = i18n.Newf(450008, "ErrVerifyCode")
	ErrSmsSendLimit                       = i18n.Newf(450009, "ErrSmsSendLimit")
	ErrVerifyFailedTooManyTimes           = i18n.Newf(450010, "ErrVerifyFailedTooManyTimes")
	ErrRobotNotFound                      = i18n.Newf(450011, "ErrRobotNotFound")
	ErrCateNotFound                       = i18n.Newf(450012, "ErrCateNotFound")
	ErrQANotFound                         = i18n.Newf(450013, "ErrQANotFound")
	ErrQAIsDeleted                        = i18n.Newf(450014, "ErrQAIsDeleted")
	ErrLockTaskFail                       = i18n.Newf(450015, "ErrLockTaskFail")
	ErrUnSupportFileType                  = i18n.Newf(450016, "ErrUnSupportFileType")
	ErrReleaseFail                        = i18n.Newf(450017, "ErrReleaseFail")
	ErrQASimilarNotFound                  = i18n.Newf(450018, "ErrQASimilarNotFound")
	ErrDocHasDeleted                      = i18n.Newf(450019, "ErrDocHasDeleted")
	ErrDocExist                           = i18n.Newf(450020, "ErrDocExist")
	ErrForbidRefer                        = i18n.Newf(450022, "ErrForbidRefer")
	ErrStatusSuccess                      = i18n.Newf(450022, "ErrStatusSuccess")
	ErrDocIsRelease                       = i18n.Newf(450023, "ErrDocIsRelease")
	ErrSystem                             = i18n.Newf(450024, "ErrSystem")
	ErrReleaseNotFound                    = i18n.Newf(450025, "ErrReleaseNotFound")
	ErrNoReleaseQA                        = i18n.Newf(450027, "ErrNoReleaseQA")
	ErrSegmentNotFound                    = i18n.Newf(450038, "ErrSegmentNotFound")
	ErrHasInAuditCorp                     = i18n.Newf(450040, "ErrHasInAuditCorp")
	ErrTaskNotFound                       = i18n.Newf(450040, "ErrTaskNotFound")
	ErrDocForbidDelete                    = i18n.Newf(450041, "ErrDocForbidDelete")
	ErrTaskIsNotInit                      = i18n.Newf(450041, "ErrTaskIsNotInit")
	ErrSegmentIsEmpty                     = i18n.Newf(450042, "ErrSegmentIsEmpty")
	ErrTaskIsStop                         = i18n.Newf(450042, "ErrTaskIsStop")
	ErrQAIsPendingRelease                 = i18n.Newf(450043, "ErrQAIsPendingRelease")
	ErrExcelIsEmpty                       = i18n.Newf(450044, "ErrExcelIsEmpty")
	ErrDocTypeForIndex                    = i18n.Newf(450045, "ErrDocTypeForIndex")
	ErrTaskMaxTryTimes                    = i18n.Newf(450045, "ErrTaskMaxTryTimes")
	ErrCorpInValid                        = i18n.Newf(450046, "ErrCorpInValid")
	ErrSegmentAlreadyExist                = i18n.Newf(450046, "ErrSegmentAlreadyExist")
	ErrReleaseIsNotPending                = i18n.Newf(450047, "ErrReleaseIsNotPending")
	ErrSegmentQAAlreadyExist              = i18n.Newf(450047, "ErrSegmentQAAlreadyExist")
	ErrDocTplNotFound                     = i18n.Newf(450049, "ErrDocTplNotFound")
	ErrDoingRelease                       = i18n.Newf(450050, "ErrDoingRelease")
	ErrExcelHead                          = i18n.Newf(450051, "ErrExcelHead")
	ErrQANotModifyFound                   = i18n.Newf(450052, "ErrQANotModifyFound")
	ErrGetTemplateFail                    = i18n.Newf(450053, "ErrGetTemplateFail")
	ErrGetDocListFail                     = i18n.Newf(450054, "ErrGetDocListFail")
	ErrUserWaitAudit                      = i18n.Newf(450055, "ErrUserWaitAudit")
	ErrLoginTimesLimit                    = i18n.Newf(450056, "ErrLoginTimesLimit")
	ErrAlreadyJoinedCorp                  = i18n.Newf(450057, "ErrAlreadyJoinedCorp")
	ErrParams                             = i18n.Newf(450057, "ErrParams")
	ErrSameDocUploading                   = i18n.Newf(450058, "ErrSameDocUploading")
	ErrRepeatCorpName                     = i18n.Newf(450059, "ErrRepeatCorpName")
	ErrSegmentNotForIndex                 = i18n.Newf(450059, "ErrSegmentNotForIndex")
	ErrReleaseType                        = i18n.Newf(450060, "ErrReleaseType")
	ErrVerifyCodeNotFound                 = i18n.Newf(450061, "ErrVerifyCodeNotFound")
	ErrReferDocFail                       = i18n.Newf(450062, "ErrReferDocFail")
	ErrFetchURLFail                       = i18n.Newf(450063, "ErrFetchURLFail")
	ErrInvalidURL                         = i18n.Newf(450064, "ErrInvalidURL")
	ErrInvalidFileName                    = i18n.Newf(450065, "ErrInvalidFileName")
	ErrInvalidAuditSource                 = i18n.Newf(450066, "ErrInvalidAuditSource")
	ErrReleaseQANotFound                  = i18n.Newf(450067, "ErrReleaseQANotFound")
	ErrUnknownSplitConfig                 = i18n.Newf(450076, "ErrUnknownSplitConfig")
	ErrUnknownMergerType                  = i18n.Newf(450077, "ErrUnknownMergerType")
	ErrFetchURLTooBig                     = i18n.Newf(450078, "ErrFetchURLTooBig")
	ErrUnknownMiniChunkType               = i18n.Newf(450079, "ErrUnknownMiniChunkType")
	ErrRobotInAudit                       = i18n.Newf(450080, "ErrRobotInAudit")
	ErrExcelContent                       = i18n.Newf(450081, "ErrExcelContent")
	ErrCateCountExceed                    = i18n.Newf(450084, "ErrCateCountExceed")
	ErrExportQA                           = i18n.Newf(450085, "ErrExportQA")
	ErrExportQATooMany                    = i18n.Newf(450086, "ErrExportQATooMany")
	ErrExportQATaskTooMany                = i18n.Newf(450087, "ErrExportQATaskTooMany")
	ErrRobotQuotaNotEnough                = i18n.Newf(450087, "ErrRobotQuotaNotEnough")
	ErrAuditFlagNotFound                  = i18n.Newf(450088, "ErrAuditFlagNotFound")
	ErrAuditFlagNotFount                  = i18n.Newf(450088, "ErrAuditFlagNotFount")
	ErrUserHasNoCorp                      = i18n.Newf(450089, "ErrUserHasNoCorp")
	ErrCateDepthExceed                    = i18n.Newf(450090, "ErrCateDepthExceed")
	ErrUserHasCorp                        = i18n.Newf(450090, "ErrUserHasCorp")
	ErrCorpIsNotInAudit                   = i18n.Newf(450091, "ErrCorpIsNotInAudit")
	ErrInvalidCateID                      = i18n.Newf(450091, "ErrInvalidCateID")
	ErrInvalidParentCateID                = i18n.Newf(450091, "ErrInvalidParentCateID")
	ErrCateNameDuplicated                 = i18n.Newf(450092, "ErrCateNameDuplicated")
	ErrStaffCorpNotMatch                  = i18n.Newf(450092, "ErrStaffCorpNotMatch")
	ErrUserHasJoinCorp                    = i18n.Newf(450093, "ErrUserHasJoinCorp")
	ErrOperateDoing                       = i18n.Newf(450094, "ErrOperateDoing")
	ErrStaffInValid                       = i18n.Newf(450095, "ErrStaffInValid")
	ErrRepeatRobotName                    = i18n.Newf(450096, "ErrRepeatRobotName")
	ErrGetReferFail                       = i18n.Newf(450098, "ErrGetReferFail")
	ErrMarkReferFail                      = i18n.Newf(450099, "ErrMarkReferFail")
	ErrAuditNotFound                      = i18n.Newf(450100, "ErrAuditNotFound")
	ErrReleaseIsNotInit                   = i18n.Newf(450101, "ErrReleaseIsNotInit")
	ErrUnknownIndexID                     = i18n.Newf(450102, "ErrUnknownIndexID")
	ErrTelephone                          = i18n.Newf(450103, "ErrTelephone")
	ErrRunningTestRecords                 = i18n.Newf(450104, "ErrRunningTestRecords")
	ErrDeleteRunningTest                  = i18n.Newf(450105, "ErrDeleteRunningTest")
	ErrInvalidSampleSetExcel              = i18n.Newf(450106, "ErrInvalidSampleSetExcel")
	ErrTestNum                            = i18n.Newf(450107, "ErrTestNum")
	ErrTestRunning                        = i18n.Newf(450108, "ErrTestRunning")
	ErrSameCreateTest                     = i18n.Newf(450109, "ErrSameCreateTest")
	ErrTestNotExist                       = i18n.Newf(450110, "ErrTestNotExist")
	ErrNoWaitJudgeRecords                 = i18n.Newf(450111, "ErrNoWaitJudgeRecords")
	ErrRecords                            = i18n.Newf(450112, "ErrRecords")
	ErrExportTaskTypeNotFound             = i18n.Newf(450115, "ErrExportTaskTypeNotFound")
	ErrRejectedQuestionNotFound           = i18n.Newf(450117, "ErrRejectedQuestionNotFound")
	ErrRejectedQuestionNotModifyFound     = i18n.Newf(450118, "ErrRejectedQuestionNotModifyFound")
	ErrCreateTest                         = i18n.Newf(450119, "ErrCreateTest")
	ErrRejectedQuestionIsPendingRelease   = i18n.Newf(450119, "ErrRejectedQuestionIsPendingRelease")
	ErrOverCharacterSizeLimit             = i18n.Newf(450120, "ErrOverCharacterSizeLimit")
	ErrOverCharacterSizeLimit4QiDian      = i18n.Newf(450120, "ErrOverCharacterSizeLimit4QiDian")
	ErrUnsatisfiedReplyNotFound           = i18n.Newf(450121, "ErrUnsatisfiedReplyNotFound")
	ErrExportUnsatisfiedReply             = i18n.Newf(450122, "ErrExportUnsatisfiedReply")
	ErrExportrUnsatisfiedReplyTooMany     = i18n.Newf(450123, "ErrExportrUnsatisfiedReplyTooMany")
	ErrUnsatisfiedReplyParams             = i18n.Newf(450124, "ErrUnsatisfiedReplyParams")
	ErrUnsatisfiedReplyAdding             = i18n.Newf(450125, "ErrUnsatisfiedReplyAdding")
	ErrAvatarURLFail                      = i18n.Newf(450126, "ErrAvatarURLFail")
	ErrTransferUnsatisfiedCountParams     = i18n.Newf(450127, "ErrTransferUnsatisfiedCountParams")
	ErrHTTPMethod                         = i18n.Newf(450128, "ErrHTTPMethod")
	ErrEmptyBody                          = i18n.Newf(450129, "ErrEmptyBody")
	ErrAuditCallbackDoing                 = i18n.Newf(450130, "ErrAuditCallbackDoing")
	ErrDocIsNotExcel                      = i18n.Newf(450131, "ErrDocIsNotExcel")
	ErrDocIsExcel                         = i18n.Newf(450132, "ErrDocIsExcel")
	ErrLoginTypeInvalid                   = i18n.Newf(450133, "ErrLoginTypeInvalid")
	ErrLoginAccountPassword               = i18n.Newf(450134, "ErrLoginAccountPassword")
	ErrLoginAccountFormat                 = i18n.Newf(450135, "ErrLoginAccountFormat")
	ErrLoginAccountExist                  = i18n.Newf(450136, "ErrLoginAccountExist")
	ErrUnknownDocType                     = i18n.Newf(450137, "ErrUnknownDocType")
	ErrAttributeLabelSystem               = i18n.Newf(450138, "ErrAttributeLabelSystem")
	ErrAttributeLabelAttrKeyInvalid       = i18n.Newf(450139, "ErrAttributeLabelAttrKeyInvalid")
	ErrAttributeLabelAttrKeyExist         = i18n.Newf(450140, "ErrAttributeLabelAttrKeyExist")
	ErrAttributeLabelAttrHasUsed          = i18n.Newf(450141, "ErrAttributeLabelAttrHasUsed")
	ErrAttributeLabelAttrNameExist        = i18n.Newf(450142, "ErrAttributeLabelAttrNameExist")
	ErrAttributeLabelAttrNameMaxLen       = i18n.Newf(450143, "ErrAttributeLabelAttrNameMaxLen")
	ErrAttributeLabelNameRepeated         = i18n.Newf(450144, "ErrAttributeLabelNameRepeated")
	ErrAttributeLabelHasRefer             = i18n.Newf(450145, "ErrAttributeLabelHasRefer")
	ErrAttributeLabelNameMaxLen           = i18n.Newf(450146, "ErrAttributeLabelNameMaxLen")
	ErrAttributeLabelLimit                = i18n.Newf(450147, "ErrAttributeLabelLimit")
	ErrAttributeLabelSimilarMaxLen        = i18n.Newf(450148, "ErrAttributeLabelSimilarMaxLen")
	ErrAttributeLabelSimilarLimit         = i18n.Newf(450149, "ErrAttributeLabelSimilarLimit")
	ErrAttributeReferLimit                = i18n.Newf(450150, "ErrAttributeReferLimit")
	ErrAttributeLabelNotFound             = i18n.Newf(450151, "ErrAttributeLabelNotFound")
	ErrAttributeLabelAttrLimit            = i18n.Newf(450152, "ErrAttributeLabelAttrLimit")
	ErrAttributeLabelUploading            = i18n.Newf(450153, "ErrAttributeLabelUploading")
	ErrAttributeLabelSource               = i18n.Newf(450154, "ErrAttributeLabelSource")
	ErrAttributeLabelRefer                = i18n.Newf(450155, "ErrAttributeLabelRefer")
	ErrDocNotAllowEdit                    = i18n.Newf(450156, "ErrDocNotAllowEdit")
	ErrAttributeLabelDocQaSync            = i18n.Newf(450157, "ErrAttributeLabelDocQaSync")
	ErrAttributeLabelUpdating             = i18n.Newf(450158, "ErrAttributeLabelUpdating")
	ErrAttributeLabelRepeated             = i18n.Newf(450159, "ErrAttributeLabelRepeated")
	ErrQANotAllowEdit                     = i18n.Newf(450160, "ErrQANotAllowEdit")
	ErrCreateAppealIng                    = i18n.Newf(450161, "ErrCreateAppealIng")
	ErrQaForbidDelete                     = i18n.Newf(450162, "ErrQaForbidDelete")
	ErrAppealNotFound                     = i18n.Newf(450163, "ErrAppealNotFound")
	ErrAuditAppealIng                     = i18n.Newf(450164, "ErrAuditAppealIng")
	ErrRetryRelease                       = i18n.Newf(450165, "ErrRetryRelease")
	ErrRetryReleaseFail                   = i18n.Newf(450166, "ErrRetryReleaseFail")
	ErrGetRelease                         = i18n.Newf(450167, "ErrGetRelease")
	ErrReleasePause                       = i18n.Newf(450168, "ErrReleasePause")
	ErrUinNotMatch                        = i18n.Newf(450169, "ErrUinNotMatch")
	ErrSystemIntegratorNotFound           = i18n.Newf(450170, "ErrSystemIntegratorNotFound")
	ErrResourcePermissionDenied           = i18n.Newf(450171, "ErrResourcePermissionDenied")
	ErrSystemIntegratorUserParams         = i18n.Newf(450172, "ErrSystemIntegratorUserParams")
	ErrFilterNotFound                     = i18n.Newf(450173, "ErrFilterNotFound")
	ErrGlobalKnowledgeNotFound            = i18n.Newf(450174, "ErrGlobalKnowledgeNotFound")
	ErrAddGlobalKnowledge                 = i18n.Newf(450175, "ErrAddGlobalKnowledge")
	ErrDelGlobalKnowledge                 = i18n.Newf(450176, "ErrDelGlobalKnowledge")
	ErrUpdGlobalKnowledge                 = i18n.Newf(450177, "ErrUpdGlobalKnowledge")
	ErrGetGlobalKnowledge                 = i18n.Newf(450178, "ErrGetGlobalKnowledge")
	ErrForceSyncGlobalKnowledge           = i18n.Newf(450179, "ErrForceSyncGlobalKnowledge")
	ErrActivateProduct                    = i18n.Newf(450180, "ErrActivateProduct")
	ErrParseFileTimeout                   = i18n.Newf(450181, "ErrParseFileTimeout")
	ErrEmptyName                          = i18n.Newf(450182, "ErrEmptyName")
	ErrEmptyAvatar                        = i18n.Newf(450183, "ErrEmptyAvatar")
	ErrDocParseTaskNotFound               = i18n.Newf(450184, "ErrDocParseTaskNotFound")
	ErrDocParseResultCallBackFail         = i18n.Newf(450185, "ErrDocParseResultCallBackFail")
	ErrDocParseResultCallBackErr          = i18n.Newf(450186, "ErrDocParseResultCallBackErr")
	ErrDocParseCharSizeExceeded           = i18n.Newf(450187, "ErrDocParseCharSizeExceeded")
	ErrDocParseCharSizeExceeded4QiDian    = i18n.Newf(450187, "ErrDocParseCharSizeExceeded4QiDian")
	ErrDocParseCosURLNotFound             = i18n.Newf(450188, "ErrDocParseCosURLNotFound")
	ErrRobotOrDocNotFound                 = i18n.Newf(450189, "ErrRobotOrDocNotFound")
	ErrUpdateDocStatusFail                = i18n.Newf(450190, "ErrUpdateDocStatusFail")
	ErrUpdateDocParseTaskStatusFail       = i18n.Newf(450191, "ErrUpdateDocParseTaskStatusFail")
	ErrCreateDocToQATaskFail              = i18n.Newf(450192, "ErrCreateDocToQATaskFail")
	ErrCreateDocToIndexTaskFail           = i18n.Newf(450193, "ErrCreateDocToIndexTaskFail")
	ErrUpdateDocStatusAndCharSizeFail     = i18n.Newf(450194, "ErrUpdateDocStatusAndCharSizeFail")
	ErrDocParseTaskFailNotFound           = i18n.Newf(450195, "ErrDocParseTaskFailNotFound")
	ErrIllegalReleaseStatus               = i18n.Newf(450196, "ErrIllegalReleaseStatus")
	ErrUpdateRobotUsedCharSizeFail        = i18n.Newf(450197, "ErrUpdateRobotUsedCharSizeFail")
	ErrExcelParseFailInDateValidity       = i18n.Newf(450198, "ErrExcelParseFailInDateValidity")
	ErrExcelParseFailNotHalfHour          = i18n.Newf(450199, "ErrExcelParseFailNotHalfHour")
	ErrDocToQaExpiredFail                 = i18n.Newf(450200, "ErrDocToQaExpiredFail")
	ErrFileExtNotMatch                    = i18n.Newf(450201, "ErrFileExtNotMatch")
	ErrRetryDocParseTaskFail              = i18n.Newf(450202, "ErrRetryDocParseTaskFail")
	ErrRobotSplitStrategyFail             = i18n.Newf(450203, "ErrRobotSplitStrategyFail")
	ErrStopDocParseFail                   = i18n.Newf(450204, "ErrStopDocParseFail")
	ErrCreateAuditFail                    = i18n.Newf(450205, "ErrCreateAuditFail")
	ErrIntentNotFound                     = i18n.Newf(450206, "ErrIntentNotFound")
	ErrCreateDocParseSplitSegmentTaskFail = i18n.Newf(450208, "ErrCreateDocParseSplitSegmentTaskFail")
	ErrCreateDocParseSplitQATaskFail      = i18n.Newf(450209, "ErrCreateDocParseSplitQATaskFail")
	ErrAttributeLabelDocQa                = i18n.Newf(450210, "ErrAttributeLabelDocQa")
	ErrTrailProductFail                   = i18n.Newf(450210, "ErrTrailProductFail")
	ErrMasterAccount                      = i18n.Newf(450211, "ErrMasterAccount")
	ErrProductPermissionNotExist          = i18n.Newf(450212, "ErrProductPermissionNotExist")
	ErrProductAlreadyOpen                 = i18n.Newf(450213, "ErrProductAlreadyOpen")
	ErrDocCannotBeSubmittedForAudit       = i18n.Newf(450215, "ErrDocCannotBeSubmittedForAudit")
	ErrDocNoNeedAudit                     = i18n.Newf(450216, "ErrDocNoNeedAudit")
	ErrEmbeddingVersionNotMatch           = i18n.Newf(450220, "ErrEmbeddingVersionNotMatch")
	ErrEmbeddingUpgrading                 = i18n.Newf(450221, "ErrEmbeddingUpgrading")
	ErrAttributeLabelNotSupported         = i18n.Newf(450222, "ErrAttributeLabelNotSupported")
	ErrAttributeBelongsToDifferentApps    = i18n.Newf(450223, "ErrAttributeBelongsToDifferentApps")
	ErrUnknownDocTypeForIndexType         = i18n.Newf(450224, "ErrUnknownDocTypeForIndexType")
	ErrAppUpgrading                       = i18n.Newf(450225, "ErrAppUpgrading")
	ErrFileSizeTooBig                     = i18n.Newf(450226, "ErrFileSizeTooBig")
	ErrAttributeLabelEmpty                = i18n.Newf(450227, "ErrAttributeLabelEmpty")
	ErrOverModelTokenLimit                = i18n.Newf(450228, "ErrOverModelTokenLimit")
	ErrBotOverCharacterSizeLimit          = i18n.Newf(450229, "ErrBotOverCharacterSizeLimit")
	ErrReqQaListExceedLimit               = i18n.Newf(450230, "ErrReqQaListExceedLimit")
	ErrAppBizIDParams                     = i18n.Newf(450231, "ErrAppBizIDParams")
	ErrGetAppFail                         = i18n.Newf(450300, "ErrGetAppFail")
	ErrAppTypeNotFound                    = i18n.Newf(450301, "ErrAppTypeNotFound")
	ErrAppQuotaNotEnough                  = i18n.Newf(450400, "ErrAppQuotaNotEnough")
	ErrAppTypeInvalid                     = i18n.Newf(450401, "ErrAppTypeInvalid")
	ErrNotFoundModel                      = i18n.Newf(450402, "ErrNotFoundModel")
	ErrAppNotFound                        = i18n.Newf(450403, "ErrAppNotFound")
	ErrAppTypeSupportFilters              = i18n.Newf(450404, "ErrAppTypeSupportFilters")
	ErrAppScenceNotSupport                = i18n.Newf(450405, "ErrAppScenceNotSupport")
	ErrAppNotSupportModelList             = i18n.Newf(450406, "ErrAppNotSupportModelList")
	ErrAppInitFail                        = i18n.Newf(450407, "ErrAppInitFail")
	ErrReleaseConfigNotFound              = i18n.Newf(450412, "ErrReleaseConfigNotFound")
	ErrCorpTrialExpired                   = i18n.Newf(450415, "ErrCorpTrialExpired")
	ErrNotInWhiteList                     = i18n.Newf(450416, "ErrNotInWhiteList")
	ErrNotDefaultModel                    = i18n.Newf(450417, "ErrNotDefaultModel")
	ErrNotInvalidModel                    = i18n.Newf(450418, "ErrNotInvalidModel")
	ErrNotAppConfig                       = i18n.Newf(450419, "ErrNotAppConfig")
	ErrAppNotPublish                      = i18n.Newf(450420, "ErrAppNotPublish")
	ErrCorpHasRegister                    = i18n.Newf(450421, "ErrCorpHasRegister")
	ErrModuleNotExist                     = i18n.Newf(450422, "ErrModuleNotExist")
	ErrCreateIntentFail                   = i18n.Newf(450426, "ErrCreateIntentFail")
	ErrUpdateIntentFail                   = i18n.Newf(450427, "ErrUpdateIntentFail")
	ErrGetIntentPolicyFail                = i18n.Newf(450428, "ErrGetIntentPolicyFail")
	ErrUpdateIntentPolicyFail             = i18n.Newf(450429, "ErrUpdateIntentPolicyFail")
	ErrCorpAppNotEqual                    = i18n.Newf(450438, "ErrCorpAppNotEqual")
	ErrFileUrlFail                        = i18n.Newf(450439, "ErrFileUrlFail")
	ErrFileUrlNotFound                    = i18n.Newf(450440, "ErrFileUrlNotFound")
	ErrAppealTypeNotMatch                 = i18n.Newf(450902, "ErrAppealTypeNotMatch")
	ErrDocQAFileFail                      = i18n.Newf(450903, "ErrDocQAFileFail")
	ErrDocIDFail                          = i18n.Newf(450904, "ErrDocIDFail")
	ErrDocFilterFlagFail                  = i18n.Newf(450905, "ErrDocFilterFlagFail")
	ErrResumeQAMaxCountLimit              = i18n.Newf(450906, "ErrResumeQAMaxCountLimit")
	ErrDocQaTaskNotFound                  = i18n.Newf(460001, "ErrDocQaTaskNotFound")
	ErrDocQaTaskStatusFail                = i18n.Newf(460002, "ErrDocQaTaskStatusFail")
	ErrGetSegmentFail                     = i18n.Newf(460003, "ErrGetSegmentFail")
	ErrGetQaExistsFail                    = i18n.Newf(460004, "ErrGetQaExistsFail")
	ErrGetListQaTaskFail                  = i18n.Newf(460005, "ErrGetListQaTaskFail")
	ErrDeleteQaTaskStatusFail             = i18n.Newf(460006, "ErrDeleteQaTaskStatusFail")
	ErrCancelQaTaskStatusFail             = i18n.Newf(460007, "ErrCancelQaTaskStatusFail")
	ErrStopQaTaskStatusFail               = i18n.Newf(460008, "ErrStopQaTaskStatusFail")
	ErrContinueQaTaskStatusFail           = i18n.Newf(460009, "ErrContinueQaTaskStatusFail")
	ErrQaTaskSegmentFail                  = i18n.Newf(460010, "ErrQaTaskSegmentFail")
	ErrQaTaskExistsOrgDataFail            = i18n.Newf(460011, "ErrQaTaskExistsOrgDataFail")
	ErrGeneratingFail                     = i18n.Newf(460012, "ErrGeneratingFail")
	ErrGeneratingNoTokenBalance           = i18n.Newf(460013, "ErrGeneratingNoTokenBalance")
	ErrModifyQaExpireFail                 = i18n.Newf(460014, "ErrModifyQaExpireFail")
	ErrModifyQaDocFail                    = i18n.Newf(460015, "ErrModifyQaDocFail")
	ErrRetryQaTaskStatusFail              = i18n.Newf(460016, "ErrRetryQaTaskStatusFail")
	ErrSynonymsNotFound                   = i18n.Newf(460018, "ErrSynonymsNotFound")
	ErrSynonymsForbidDelete               = i18n.Newf(460019, "ErrSynonymsForbidDelete")
	ErrExportSynonyms                     = i18n.Newf(460020, "ErrExportSynonyms")
	ErrExportSynonymsTooMany              = i18n.Newf(460021, "ErrExportSynonymsTooMany")
	ErrSynonymsInvalidStandard            = i18n.Newf(460022, "ErrSynonymsInvalidStandard")
	ErrSynonymsInvalidWord                = i18n.Newf(460023, "ErrSynonymsInvalidWord")
	ErrSynonymsTooMany                    = i18n.Newf(460024, "ErrSynonymsTooMany")
	ErrSynonymsIsDeleted                  = i18n.Newf(460025, "ErrSynonymsIsDeleted")
	ErrSynonymsListUploading              = i18n.Newf(460026, "ErrSynonymsListUploading")
	ErrSynonymsInvalidDupError            = i18n.Newf(460027, "ErrSynonymsInvalidDupError")
	ErrSynonymsTaskNotFound               = i18n.Newf(460028, "ErrSynonymsTaskNotFound")
	ErrSynonymsTaskImportFailWithConflict = i18n.Newf(460029, "ErrSynonymsTaskImportFailWithConflict")
	ErrAppealCallbackDoing                = i18n.Newf(460030, "ErrAppealCallbackDoing")
	ErrDescribeDocLimit                   = i18n.Newf(460031, "ErrDescribeDocLimit")
	ErrCreateQADocType                    = i18n.Newf(460032, "ErrCreateQADocType")
	ErrStopTestStatus                     = i18n.Newf(460033, "ErrStopTestStatus")
	ErrRetryTestStatus                    = i18n.Newf(460034, "ErrRetryTestStatus")
	ErrDocCannotRename                    = i18n.Newf(460035, "ErrDocCannotRename")
	ErrGenerateSimilarParams              = i18n.Newf(460035, "ErrGenerateSimilarParams")
	ErrDocSegmentPrefixNotMatch           = i18n.Newf(460036, "ErrDocSegmentPrefixNotMatch")
	ErrDocNameNotMatch                    = i18n.Newf(460037, "ErrDocNameNotMatch")
	ErrDocNameExtNotMatch                 = i18n.Newf(460038, "ErrDocNameExtNotMatch")
	ErrDocNameVerifyFailed                = i18n.Newf(460039, "ErrDocNameVerifyFailed")
	ErrDocNameNotChanged                  = i18n.Newf(460040, "ErrDocNameNotChanged")
	ErrDocDiffDocNotFound                 = i18n.Newf(460041, "ErrDocDiffDocNotFound")
	ErrCreateDocDiffTaskFail              = i18n.Newf(460042, "ErrCreateDocDiffTaskFail")
	ErrCreateDocDiffTaskInTaskFail        = i18n.Newf(460043, "ErrCreateDocDiffTaskInTaskFail")
	ErrCreateDocDiffTaskInQaFail          = i18n.Newf(460044, "ErrCreateDocDiffTaskInQaFail")
	ErrCreateDocDiffTaskDescribeFail      = i18n.Newf(460045, "ErrCreateDocDiffTaskDescribeFail")
	ErrHandleDocDiffSizeFail              = i18n.Newf(460046, "ErrHandleDocDiffSizeFail")
	ErrHandleDocDiffFail                  = i18n.Newf(460047, "ErrHandleDocDiffFail")
	ErrHandleDocDiffNotFound              = i18n.Newf(460048, "ErrHandleDocDiffNotFound")
	ErrHandleDocDiffNotFail               = i18n.Newf(460049, "ErrHandleDocDiffNotFail")
	ErrDocDiffQaNotRetry                  = i18n.Newf(460050, "ErrDocDiffQaNotRetry")
	ErrCreateDocDiffTaskDocTypeFail       = i18n.Newf(460051, "ErrCreateDocDiffTaskDocTypeFail")
	ErrDocDiffTaskRunIng                  = i18n.Newf(460052, "ErrDocDiffTaskRunIng")
	ErrHandleDiffTypeOperationFail        = i18n.Newf(460053, "ErrHandleDiffTypeOperationFail")
	ErrHandleDocOperationFail             = i18n.Newf(460054, "ErrHandleDocOperationFail")
	ErrHandleQaOperationFail              = i18n.Newf(460055, "ErrHandleQaOperationFail")
	ErrHandleQaOperationReNameFail        = i18n.Newf(460056, "ErrHandleQaOperationReNameFail")
	ErrDocIsModifyingOrDeleting           = i18n.Newf(460057, "ErrDocIsModifyingOrDeleting")
	ErrQaIsModifyingOrDeleting            = i18n.Newf(460058, "ErrQaIsModifyingOrDeleting")
	ErrVideoURLFail                       = i18n.Newf(470100, "ErrVideoURLFail")
	ErrInvalidDocQaExcel                  = i18n.Newf(470101, "ErrInvalidDocQaExcel")
	ErrGenerateQALimitFail                = i18n.Newf(470102, "ErrGenerateQALimitFail")
	ErrHandleDocDiffTaskInDiffFail        = i18n.Newf(470103, "ErrHandleDocDiffTaskInDiffFail")
	ErrHandleDocDiffTaskDocTypeFail       = i18n.Newf(470104, "ErrHandleDocDiffTaskDocTypeFail")
	ErrHandleDocDiffTaskTypeFail          = i18n.Newf(470105, "ErrHandleDocDiffTaskTypeFail")
	ErrHandleDocDiffTaskDocNotFoundFail   = i18n.Newf(470106, "ErrHandleDocDiffTaskDocNotFoundFail")
	ErrInvalidExpireTime                  = i18n.Newf(470107, "ErrInvalidExpireTime")
	ErrUserIdInCustomVariablesIsEmpty     = i18n.Newf(470108, "ErrUserIdInCustomVariablesIsEmpty")
	ErrReleaseMaxCount                    = i18n.Newf(470109, "ErrReleaseMaxCount")
	ErrGetReleaseFail                     = i18n.Newf(470110, "ErrGetReleaseFail")

	ErrContextInvalid                    = i18n.Newf(471003, "ErrContextInvalid")
	ErrParameterInvalid                  = i18n.Newf(471004, "ErrParameterInvalid")
	ErrRelatedAppExist                   = i18n.Newf(471005, "ErrRelatedAppExist")
	ErrCreateSharedKnowledgeAppFailed    = i18n.Newf(471006, "ErrCreateSharedKnowledgeAppFailed")
	ErrDeleteSharedKnowledgeAppFailed    = i18n.Newf(471007, "ErrDeleteSharedKnowledgeAppFailed")
	ErrGetUserNameFailed                 = i18n.Newf(471008, "ErrGetUserNameFailed")
	ErrCreateSharedKnowledgeRecordFailed = i18n.Newf(471009, "ErrCreateSharedKnowledgeRecordFailed")
	ErrQuerySharedKnowledgeRecordFailed  = i18n.Newf(471010, "ErrQuerySharedKnowledgeRecordFailed")
	ErrSharedKnowledgeConvertFailed      = i18n.Newf(471011, "ErrSharedKnowledgeConvertFailed")
	ErrGetShareKnowledgeAppListFailed    = i18n.Newf(471012, "ErrGetShareKnowledgeAppListFailed")
	ErrDeleteSharedKnowledgeRecordFailed = i18n.Newf(471013, "ErrDeleteSharedKnowledgeRecordFailed")
	ErrSharedKnowledgeRecordNotFound     = i18n.Newf(471014, "ErrSharedKnowledgeRecordNotFound")
	ErrKnowledgeSchemaTaskNotFound       = i18n.Newf(471015, "ErrKnowledgeSchemaTaskNotFound")
	ErrSharedKnowledgeExist              = i18n.Newf(471016, "ErrSharedKnowledgeExist")
	ErrSharedKnowledgeNameQueryFailed    = i18n.Newf(471017, "ErrSharedKnowledgeNameQueryFailed")
	ErrReleaseQaMaxCount                 = i18n.Newf(471018, "ErrReleaseQaMaxCount")
	ErrBatchDownloadMaxCount             = i18n.Newf(471019, "ErrBatchDownloadMaxCount")
	ErrQueryKnowledgeModelConfigFailed   = i18n.Newf(471020, "ErrQueryKnowledgeModelConfigFailed")
	ErrDeleteKnowledgeModelConfigFailed  = i18n.Newf(471021, "ErrDeleteKnowledgeModelConfigFailed")
	ErrAttributeLabelReferLimit          = i18n.Newf(471022, "ErrAttributeLabelReferLimit")
	ErrDocStatusNotStable                = i18n.Newf(471023, "ErrDocStatusNotStable")
	ErrDescribeServiceRoleFailed         = i18n.Newf(471024, "ErrDescribeServiceRoleFailed")
	ErrServiceRoleUnavailable            = i18n.Newf(471025, "ErrServiceRoleUnavailable")
	ErrAssumeServiceRoleFailed           = i18n.Newf(471026, "ErrAssumeServiceRoleFailed")
	ErrUserCOSNotReadyFailed             = i18n.Newf(471027, "ErrUserCOSNotReadyFailed")
	ErrListBucketWithCORSFailed          = i18n.Newf(471028, "ErrListBucketWithCORSFailed")
	ErrRefreshCorpCOSDocStatusFail       = i18n.Newf(471029, "ErrRefreshCorpCOSDocStatusFail")
	ErrRefreshCorpCOSDocUserAuthFail     = i18n.Newf(471030, "ErrRefreshCorpCOSDocUserAuthFail")
	ErrRefreshCorpCOSDocFail             = i18n.Newf(471031, "ErrRefreshCorpCOSDocFail")

	// 连接外部数据库的错误码
	ErrOpenDbSourceFail              = i18n.Newf(4720000, "ErrOpenDbSourceFail")
	ErrDbSourceTypeNotSupport        = i18n.Newf(4720001, "ErrDbSourceTypeNotSupport")
	ErrDbSourceTableBlankFail        = i18n.Newf(4720002, "ErrDbSourceTableBlankFail")
	ErrTypeConvertFail               = i18n.Newf(4720003, "ErrTypeConvertFail")
	ErrAddDbSourceFail               = i18n.Newf(4720004, "ErrAddDbSourceFail")
	ErrUpdateDbSourceGetFail         = i18n.Newf(4720005, "ErrUpdateDbSourceGetFail")
	ErrUpdateDbSourceCreateFail      = i18n.Newf(4720006, "ErrUpdateDbSourceCreateFail")
	ErrPageNumberInvalid             = i18n.Newf(4720007, "ErrPageNumberInvalid")
	ErrDataNotExistOrIsDeleted       = i18n.Newf(4720008, "ErrDataNotExistOrIsDeleted")
	ErrDbTableNumIsInvalid           = i18n.Newf(4720009, "ErrDbTableNumIsInvalid")
	ErrNameInvalid                   = i18n.Newf(4720010, "ErrNameInvalid")
	ErrDbNameBanned                  = i18n.Newf(4720011, "ErrDbNameBanned")
	ErrDbNameIsInvalid               = i18n.Newf(4720012, "ErrDbNameIsInvalid")
	ErrPasswordDecodeFail            = i18n.Newf(4720013, "ErrPasswordDecodeFail")
	ErrDbSourceTimeOut               = i18n.Newf(4720014, "ErrDbSourceTimeOut")
	ErrDbSourceNoPermission          = i18n.Newf(4720015, "ErrDbSourceNoPermission")
	ErrDbSourceTableEmpty            = i18n.Newf(4720016, "ErrDbSourceTableEmpty")
	ErrDataBase                      = i18n.Newf(4720017, "ErrDataBase")
	ErrInvalidFields                 = i18n.Newf(4720018, "ErrInvalidFields")
	ErrWriteIntoEsFail               = i18n.Newf(4720019, "ErrWriteIntoEsFail")
	ErrDbTableSizeInvalid            = i18n.Newf(4720020, "ErrDbTableSizeInvalid")
	ErrDbSourceInputExtraLong        = i18n.Newf(4720021, "ErrDbSourceInputExtraLong")
	ErrDbSourceParsingFailed         = i18n.Newf(4720022, "ErrDbSourceParsingFailed")
	ErrDbSourceTableColumnNotExist   = i18n.Newf(4720023, "ErrDbSourceTableColumnNotExist")
	ErrDbSourceNotEnabled            = i18n.Newf(4720024, "ErrDbSourceNotEnabled")
	ErrDbTableStatus                 = i18n.Newf(4720025, "ErrDbTableStatus")
	ErrDbTableIsNotExist             = i18n.Newf(4720026, "ErrDbTableIsNotExist")
	ErrDbSourceLimitExceeded         = i18n.Newf(4720027, "ErrDbSourceLimitExceeded")
	ErrDbTableStatusForText2Sql      = i18n.Newf(4720028, "ErrDbTableStatusForText2Sql")
	ErrText2sqlTableNums             = i18n.Newf(4720029, "ErrText2sqlTableNums")
	ErrDbSourceStatusForChangeEnable = i18n.Newf(4720030, "ErrDbSourceStatusForChangeEnable")
	ErrDbTableNotExistForProd        = i18n.Newf(4720031, "ErrDbTableNotExistForProd")
	ErrDbSourceStatusForText2Sql     = i18n.Newf(4720032, "ErrDbSourceStatusForText2Sql")
	ErrText2sqlTimeOut               = i18n.Newf(4720033, "ErrText2sqlTimeOut")
	ErrInvalidDbSourceHost           = i18n.Newf(4720034, "ErrInvalidDbSourceHost")

	//权限相关报错
	ErrCommonFail                          = i18n.Newf(470107, "ErrCommonFail")
	ErrCustUserNameFail                    = i18n.Newf(470108, "ErrCustUserNameFail")
	ErrThirdUserIdFail                     = i18n.Newf(470109, "ErrThirdUserIdFail")
	ErrCustUserNameExist                   = i18n.Newf(470110, "ErrCustUserNameExist")
	ErrLkeUserIdExist                      = i18n.Newf(470111, "ErrLkeUserIdExist")
	ErrUserRoleEmpty                       = i18n.Newf(470112, "ErrUserRoleEmpty")
	ErrCreateUserFail                      = i18n.Newf(470113, "ErrCreateUserFail")
	ErrUserNotExist                        = i18n.Newf(470113, "ErrUserNotExist")
	ErrBatchEditUserId                     = i18n.Newf(470114, "ErrBatchEditUserId")
	ErrUpdateUserFail                      = i18n.Newf(470115, "ErrUpdateUserFail")
	ErrGetUserListFail                     = i18n.Newf(470116, "ErrGetUserListFail")
	ErrGetUserRoleListFail                 = i18n.Newf(470117, "ErrGetUserRoleListFail")
	ErrGetRoleListFail                     = i18n.Newf(470118, "ErrGetRoleListFail")
	ErrDetailUserFail                      = i18n.Newf(470118, "ErrDetailUserFail")
	ErrDeleteUserFail                      = i18n.Newf(470118, "ErrDeleteUserFail")
	ErrDeleteUserRoleFail                  = i18n.Newf(470119, "ErrDeleteUserRoleFail")
	ErrGetUserConfigFail                   = i18n.Newf(470120, "ErrGetUserConfigFail")
	ErrSetCustUserConfigFail               = i18n.Newf(470121, "ErrSetCustUserConfigFail")
	ErrSetThirdAclNotToken                 = i18n.Newf(470122, "ErrSetThirdAclNotToken")
	ErrSetThirdAclNotSecret                = i18n.Newf(470123, "ErrSetThirdAclNotSecret")
	ErrSetThirdAclTypeFail                 = i18n.Newf(470124, "ErrSetThirdAclTypeFail")
	ErrSetThirdAclTokenUrlFail             = i18n.Newf(470125, "ErrSetThirdAclTokenUrlFail")
	ErrSetThirdAclAclUrlFail               = i18n.Newf(470126, "ErrSetThirdAclAclUrlFail")
	ErrSetThirdAclFail                     = i18n.Newf(470127, "ErrSetThirdAclFail")
	ErrGetThirdAclFail                     = i18n.Newf(470128, "ErrGetThirdAclFail")
	ErrRoleNameFail                        = i18n.Newf(470129, "ErrRoleNameFail")
	ErrRoleNameExist                       = i18n.Newf(470130, "ErrRoleNameExist")
	ErrRoleSearchTypeFail                  = i18n.Newf(470131, "ErrRoleSearchTypeFail")
	ErrRoleKnowledgeFail                   = i18n.Newf(470132, "ErrRoleKnowledgeFail")
	ErrRoleKnowledgeTypeFail               = i18n.Newf(470133, "ErrRoleKnowledgeTypeFail")
	ErrDeleteRoleFail                      = i18n.Newf(470134, "ErrDeleteRoleFail")
	ErrRoleNotExist                        = i18n.Newf(470135, "ErrRoleNotExist")
	ErrRoleModifyFail                      = i18n.Newf(470136, "ErrRoleModifyFail")
	ErrSetCustUserConfigRoleFail           = i18n.Newf(470137, "ErrSetCustUserConfigRoleFail")
	ErrSetThirdAclConfigLock               = i18n.Newf(470138, "ErrSetThirdAclConfigLock")
	ErrSetAppShareKGFailed                 = i18n.Newf(470139, "ErrSetAppShareKGFailed")
	ErrGetAppShareKGListFailed             = i18n.Newf(470140, "ErrGetAppShareKGListFailed")
	ErrRetrieveBaseSharedKGFailed          = i18n.Newf(470141, "ErrRetrieveBaseSharedKGFailed")
	ErrGetAppFailed                        = i18n.Newf(470142, "ErrGetAppFailed")
	ErrGetKnowledgeFailed                  = i18n.Newf(470143, "ErrGetKnowledgeFailed")
	ErrDocIsDisabled                       = i18n.Newf(470144, "ErrDocIsDisabled")
	ErrDocIsEnabled                        = i18n.Newf(470145, "ErrDocIsEnabled")
	ErrRoleConditionFail                   = i18n.Newf(470146, "ErrRoleConditionFail")
	ErrRoleTypeFail                        = i18n.Newf(470147, "ErrRoleTypeFail")
	ErrQAIsDisabled                        = i18n.Newf(470148, "ErrQAIsDisabled")
	ErrQAIsEnabled                         = i18n.Newf(470149, "ErrQAIsEnabled")
	ErrUserMaxLimit                        = i18n.Newf(470150, "ErrUserMaxLimit")
	ErrRoleMaxLimit                        = i18n.Newf(470151, "ErrRoleMaxLimit")
	ErrGetDocSegmentTooLarge               = i18n.Newf(470152, "ErrGetDocSegmentTooLarge")
	ErrDocSegmentNotFound                  = i18n.Newf(470153, "ErrDocSegmentNotFound")
	ErrDocSegmentKeywordsMaxLimit          = i18n.Newf(470154, "ErrDocSegmentKeywordsMaxLimit")
	ErrGetEmbedding                        = i18n.Newf(470155, "ErrGetEmbedding")
	ErrGetEmbeddingEmpty                   = i18n.Newf(470156, "ErrGetEmbeddingEmpty")
	ErrDocNotSupportInterveneFailed        = i18n.Newf(470157, "ErrDocNotSupportInterveneFailed")
	ErrDocSegmentOperationNotAllowedFailed = i18n.Newf(470158, "ErrDocSegmentOperationNotAllowedFailed")
	ErrDocSegmentSheetNotFound             = i18n.Newf(470159, "ErrDocSegmentSheetNotFound")
	ErrCateTypeFail                        = i18n.Newf(470160, "ErrCateTypeFail")
	ErrDocSegmentFilterInvalid             = i18n.Newf(470161, "ErrDocSegmentFilterInvalid")
	ErrRefreshTxDocStatusFail              = i18n.Newf(470162, "ErrRefreshTxDocStatusFail")
	ErrRefreshTxDocUserAuthFail            = i18n.Newf(470163, "ErrRefreshTxDocUserAuthFail")
	ErrRefreshTxDocFail                    = i18n.Newf(470164, "ErrRefreshTxDocFail")
	ErrInterveneDataFail                   = i18n.Newf(470165, "ErrInterveneDataFail")
	ErrEmbeddingModelUpdating              = i18n.Newf(470166, "ErrEmbeddingModelUpdating")
	ErrEmbeddingModelUpdateFailed          = i18n.Newf(470167, "ErrEmbeddingModelUpdateFailed")
	ErrTxDownloadDocFailed                 = i18n.Newf(470168, "ErrTxDownloadDocFailed")
	ErrDescribeExceededKnowledgeListFailed = i18n.Newf(470169, "ErrDescribeExceededKnowledgeListFailed")
	ErrResumeExceedKnowledgeFailed         = i18n.Newf(470170, "ErrResumeExceedKnowledgeFailed")

	// 下面的7位错误码不要再增加了，接着上面的6位错误码继续加
	ErrQAIsNotExist                = i18n.Newf(4500141, "ErrQAIsNotExist")
	ErrRealtimeDocParseFailed      = i18n.Newf(4505001, "ErrRealtimeDocParseFailed")
	ErrParamsNotExpected           = i18n.Newf(4505002, "ErrParamsNotExpected")
	ErrDocCharSizeNotAllowCreateQA = i18n.Newf(4506001, "ErrDocCharSizeNotAllowCreateQA")
	ErrRetrievalConfig             = i18n.Newf(4507001, "ErrRetrievalConfig")
	ErrNoTokenBalance              = i18n.Newf(4507002, "ErrNoTokenBalance")
	ErrDocNotStable                = i18n.Newf(4508000, "ErrDocNotStable")
	ErrQANotStable                 = i18n.Newf(4508001, "ErrQANotStable")
)

// TMsgDataCountReqError 数据统计校验报错封装
func TMsgDataCountReqError(msg string) error {
	return errs.New(450600, msg)
}

// ErrWrapf 错误封装
func ErrWrapf(err error, format string, args ...interface{}) error {
	return i18n.Newf(errs.Code(err), format, args...)
}

// ErrWrapf 错误封装
func ErrWrapWithMsgf(err error, format string, args ...interface{}) error {
	return errs.Wrapf(err, errs.Code(err), errs.Msg(err)+format, args...)
}

// ConvertErrMsg 转换错误信息，可根据集成商需求定制错误信息
func ConvertErrMsg(systemIntegratorName string, err error) error {
	if errMap, ok1 := ErrMap[systemIntegratorName]; ok1 {
		if newErr, ok2 := errMap[err]; ok2 {
			return newErr
		}
	}
	return err
}

// Is 判断err是否相等
func Is(err, target error) bool {
	return errors.Is(err, target) || errs.Code(err) == errs.Code(target)
}
